### ISSUE TITLE
[Bug Report] Input with number type still being validated even if it's not required

### ISSUE THREAD

**Issue by llavre** [ElemeFE/element#10305]
### Element UI version
2.2.2

### OS/Browsers version
Windows 10,  Chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/t0s7onfj/](https://jsfiddle.net/t0s7onfj/)

### Steps to reproduce
Do not fill any information in number input and press "submit"

### What is Expected?
Do not validate not required number input

### What is actually happening?
Not required number input is being validated

**Comment by Leopoldthecoder** [comment]
I tested with pure `async-validator`, turns out this is how it handles such situation:
```js
import Schema from 'async-validator'
const descriptor = {
  name: { type: 'number' }
}
const validator = new Schema(descriptor)
validator.validate({ name: '' }, (errors, fields) => {
  console.log(errors, fields)
})
```

![image](https://user-images.githubusercontent.com/10095631/37817793-fa95f27a-2eb2-11e8-90be-0650408cc0ae.png)

For `async-validator`, this may not be a bug. You can workaround with a RegExp: https://jsfiddle.net/leopoldthecuber/t0s7onfj/13/ , or set the initial value to `null`: https://jsfiddle.net/leopoldthecuber/t0s7onfj/16/.
