### ISSUE TITLE
[Bug Report] form pattern validate not prevent the from submit when the input is empty

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#10763]
### Element UI version
2.3.4

### OS/Browsers version
mac

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/vc7g1skv/1/](https://jsfiddle.net/vc7g1skv/1/)

### Steps to reproduce
click the submit button

### What is Expected?
error message should be shown, and the submit should fail

### What is actually happening?
input is shown with red color, no error message is shown, and the submit success

**Comment by wacky6** [comment]
Looks like this is caused by `async-validator`'s design, see line 18 in https://github.com/yiminghe/async-validator/blob/master/src/validator/string.js 

I suggest you raise this issue upstream if you think this is a bug rather than a feature.

For now, add `required`, or write a custom validator should solve your problem. https://jsfiddle.net/vc7g1skv/7/
