### ISSUE TITLE
[Bug Report] Update the popper.js

### ISSUE THREAD

**Issue by akki-jat** [ElemeFE/element#11194]
### Existing Component
Yes

### Component Name
popper.js

### Description
Gives error when element-ui's component is used in shadowDom (error in getStyleComputedProperty.js which they have updated for shadowDom)

**Comment by ziyoung** [comment]
Please provide a repro.

**Comment by akki-jat** [comment]
@ziyoung I am little busy, but I will provide a repo by end of today

**Comment by akki-jat** [comment]
Hi @ziyoung, here is the link for reproduce the error : [https://codesandbox.io/s/8n44wp842l](url)
And as you will see there are extra error when element-ui's select component is used with shadowDom

**Comment by akki-jat** [comment]
Hi @ziyoung, is there any progress?

**Comment by ziyoung** [comment]
The [poper.js](https://github.com/ElemeFE/element/blob/dev/src/utils/popper.js) used in element-ui is outdated, but [the latest version](https://www.npmjs.com/package/popper.js) works fine with shadow dom. We can't use the latest poper.js directly because we have modified it. Fixing this problem will cost me some time.

**Comment by akki-jat** [comment]
@ziyoung ok, but make it fast, I love element-ui but I can't use it because of this issue
