### ISSUE TITLE
[Bug Report] merge the column table,click the first column will disappear, move forward a row.

### ISSUE THREAD

**Issue by yangbospton** [ElemeFE/element#12034]
### Element UI version
2.4.4

### OS/Browsers version
windows10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3822/](https://jsfiddle.net/mmx38qxw/3822/)

### Steps to reproduce
Click the configuration two，merge the column table,click the first column will disappear, move forward a row.

### What is Expected?
Clicking the form of the merged column, the form does not change

### What is actually happening?
Clicking the form of the merged column, the table has changed

**Comment by jikkai** [comment]
Could you please explain your problem in detail, I can't catch your issue.

**Comment by yangbospton** [comment]
In the merge of table columns, one column will disappear when clicking the table. You can try to see my example @jikkai

**Comment by elfman** [comment]
@yangbospton this bug seems cause by your code, not Element.
After first call `objectSpanMethod`, you set `render` to `true`, and return { num, 1 }. When user click on the cell, `el-table` will call `objectSpanMethod` again, and it will return { 0, 0 }, so the first column is disappeared.
You should change your code

**Comment by yangbospton** [comment]
ok,thank you @elfman
