### ISSUE TITLE
[Bug Report] date-picker下拉框位置错误

### ISSUE THREAD

**Issue by Kinghts** [ElemeFE/element#12261]
### Element UI version
2.4.5

### OS/Browsers version
win10   firefox 61

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4655/](https://jsfiddle.net/mmx38qxw/4655/)

### Steps to reproduce

点击‘切换’后，再点击date-picker会发现弹出层位置不正确，它的position变为fixed了

### What is Expected?
date-picker弹出层位置正确

### What is actually happening?
date-picker弹出层位置不正确

**Comment by wacky6** [comment]
Caused by: https://github.com/vuejs/vue/issues/3467 , also refer to https://github.com/vuejs/vue/issues/2873. $refs is no longer reactive.

Need to rewrite vue-popper implementation to get component reference every time. Should check and deprecate all usage of `$refs` in computed property.

@jikkai I recommend this issue to be considered for 3.0 milestone.

**Comment by Kinghts** [comment]
暂时只能用v-show代替v-if了

**Comment by elfman** [comment]
这个并不算Element的bug，你在v-if与v-else中使用了同一种Component，这两个Component属性也基本一致，所以Vue计算Virtual Dom的diff时认为它们没有发生改变，没有把内部引用的`this.$refs.reference`修改过来，计算popover的位置出错。
解决的方法是在两个`DatePicker`上加上key属性，明确告知Vue这是两个不同的组件，[https://jsfiddle.net/HarlanLuo/mmx38qxw/6731/](https://jsfiddle.net/HarlanLuo/mmx38qxw/6731/)
