### ISSUE TITLE
[Bug Report] Table collapse all rows after remove element from table

### ISSUE THREAD

**Issue by industral** [ElemeFE/element#12292]
### Element UI version
2.4.5

### OS/Browsers version
Any

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4760/](https://jsfiddle.net/mmx38qxw/4760/)

### Steps to reproduce
1. Go to https://jsfiddle.net/mmx38qxw/4760/
2. Expand all rows
3. Click on first button
4. Element is removed. All rows are collapsed

The same with button #2

### What is Expected?
Rows should keep their actual state. If they are expanded, they should still expanded.

### What is actually happening?
All rows collapsed, when any removal action happens.

**Comment by JserWang** [comment]
In your demo, you can set `row-key="title"` for the table.
Because in the table store, `expandRows` needs to be saved by `rowKey`.

[https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-store.js#L174-L184](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-store.js#L174-L184)

**Comment by industral** [comment]
Man you rock! Thanks! That definitely has to be added to documentation.
