### ISSUE TITLE
[Bug Report] Tab underline is missing

### ISSUE THREAD

**Issue by jardenliu** [ElemeFE/element#13811]
### Element UI version
2.4.11

### OS/Browsers version
windows/chrome70

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/tabs 全部下滑线丢失了
![image](https://user-images.githubusercontent.com/15191056/50147621-99125480-02f1-11e9-9d77-eab9434a0c37.png)

### What is Expected?
有下划线
![image](https://user-images.githubusercontent.com/15191056/50147707-c65f0280-02f1-11e9-973f-f555732b8cd5.png)

### What is actually happening?
有下划线

**Comment by GenevievePlantin** [comment]
It seems that the computed "barStyle" variable doesn't see the `this.$parent.$refs.tabs` changes and returns an empty style without computing it again when the `this.$parent.$refs.tabs` finally loads.

I changed the line `if (!this.$parent.$refs.tabs) return {};` for `if (!this.tabs && !this.$parent.$refs.tabs) return {};` (in the tab-bar.vue file) and it works for me now, because the observer in "this.tabs" forces the computed variable (barStyle) to rerender when I "this.tabs" is filled. 

I didn't test if it still works when tabs are empty for real though.
