### ISSUE TITLE
[Bug Report] Bug in el-table sort-method

### ISSUE THREAD

**Issue by Holybasil** [ElemeFE/element#13842]
### Element UI version
2.1.0

### OS/Browsers version
Chrome 71.0.3578.98

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/Holybasil/pqkn05s6/4/](https://jsfiddle.net/Holybasil/pqkn05s6/4/)

### Steps to reproduce
See jsfiddle and try to release comments in methods[test]

### What is Expected?
Same to https://jsfiddle.net/2mjjx3n8/3/
Refer https://github.com/ElemeFE/element/issues/5117

### What is actually happening?
Not work and just reverse the list

**Comment by foster066** [comment]
I've discovered the same issue and found that this was broken in element-ui v2.0.2. I use the same fiddle with v2.0.1 and it works perfectly.
I have two fields - date in text and the sortable date in format YYYY-MM. Sorting should work the same on both columns - it uses one sort function. In v2.0.2 sorting looks random but was working fine previously.
You can check:
**v2.0.2 doesn't work properly** - https://jsfiddle.net/q3soynb0/
v2.0.1 works properly - https://jsfiddle.net/q3soynb0/1/

**Comment by jonimoas** [comment]
fell on this same issue, solved it by using the sort-change attribute as follows:

1)Add a @sort-change="FunctionName" on the el-table tag
2)Add the sortable attribute on the column you wish to sort
3)Write a function that sorts and returns the table's datasource, 
e.x. public FunctionName(){return this.tableData.sort(...);}

note: according to the documentation, you can pass the column to the function, in order to adapt your sorting needs accordingly. 

I know that this is not a fix per se, but it is a decent workaround for now.
