### ISSUE TITLE
[Bug Report] InputNumber enters numbers directly under IE11, V-model does not work

### ISSUE THREAD

**Issue by squallliu** [ElemeFE/element#14209]
### Element UI version
2.4.11

### OS/Browsers version
Windows7/IE11

### Vue version
2.5.22

### Reproduction Link
[http://element.eleme.io/#/en-US/component/input-number](http://element.eleme.io/#/en-US/component/input-number)

### Steps to reproduce
1、直接输入数字
2、失去焦点

### What is Expected?
控制台打印值

### What is actually happening?
不打印

**Comment by Ende93** [comment]
ie11 on win10 work well.

**Comment by Ende93** [comment]
https://github.com/ElemeFE/element/blob/15b57cbb2234eb93a648e9bac900cbf87a388e20/packages/input/src/input.vue#L287-L292
是的这种写法有点问题，另外，这是 2.5 版本的，你 `reporoduction link` 应该换个，官网的还是 2.4

**Comment by TeroBlaZe** [comment]
I want to share my experience on the issue. Actually the problem is also reproducible in Edge 44 on versions of ElementUI 2.5.x but the 2.4.11 from the NPM is the last working version except one thing. For some reason even the version 2.4.11 used in the examples on the website doesn't work as expected.

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by oldDirver001** [comment]
Edge同样出现这个问题

**Comment by squallliu** [comment]
2.6.3已经解决了
