### ISSUE TITLE
[Bug Report] Firefox Browser，<el-input type="number"></el-input> Cannot enter 0.01

### ISSUE THREAD

**Issue by sybgfhcd** [ElemeFE/element#14438]
### Element UI version
2.5.4

### OS/Browsers version
window 10 / Firefox 61

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/72ob30gv/](https://jsfiddle.net/72ob30gv/)

### Steps to reproduce
in the jsfiddle

### What is Expected?
<el-input type="number"></el-input> in the Firefox can enter 0.01

### What is actually happening?
<el-input type="number"></el-input> in the Firefox can not enter 0.01

**Comment by wacky6** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values

For numerical input, use input-number is recommended.

**Comment by island205** [comment]
Input is a controlled component, it **always shows Vue binding value**.

Under normal circumstances, input event should be handled. Its handler should update component's binding value (or use `v-model`). Otherwise, input box's value will not change.

Do not support `v-model` modifiers.

http://element.eleme.io/#/en-US/component/input

**Comment by askart** [comment]
> Input is a controlled component, it **always shows Vue binding value**.
> 
> Under normal circumstances, input event should be handled. Its handler should update component's binding value (or use `v-model`). Otherwise, input box's value will not change.
> 
> Do not support `v-model` modifiers.
> 
> http://element.eleme.io/#/en-US/component/input

v-model .number and .trim modifiers work
