### ISSUE TITLE
[Bug Report] el-input type="number" use v-model.number Can't input 0.0xx

### ISSUE THREAD

**Issue by qa2080639** [ElemeFE/element#14466]
### Element UI version
2.5.4

### OS/Browsers version
Win10 x64 chrome70

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/57z6a4fj/](https://jsfiddle.net/57z6a4fj/)

### Steps to reproduce
原生input使用v-model.number能输入0.001
el-input输入到0.0时会删掉后面的0导致不能输入0.001

### What is Expected?
el-input和原生一样能输入0.00x 不对用户输入的数据进行删除

### What is actually happening?
el-input会删除0.x后面的0

**Comment by island205** [comment]
Input 为受控组件，它总会显示 Vue 绑定值。

通常情况下，应当处理 input 事件，并更新组件的绑定值（或使用v-model）。否则，输入框内显示的值将不会改变。

不支持 v-model 修饰符。

http://element.eleme.io/#/zh-CN/component/input

**Comment by island205** [comment]
Input is a controlled component, it **always shows Vue binding value**.

Under normal circumstances, input event should be handled. Its handler should update component's binding value (or use `v-model`). Otherwise, input box's value will not change.

Do not support `v-model` modifiers.

http://element.eleme.io/#/en-US/component/input

**Comment by chenquan1992** [comment]
请问一下，应该怎么处理呢？
