### ISSUE TITLE
[Feature Request] Support multiple column sort on table component natively

### ISSUE THREAD

**Issue by liloxboy** [ElemeFE/element#14482]
### Existing Component
Yes

### Component Name
el-table

### Description
The el-table component supports single column sort by default, which is already awesome. However, under some circumstances, we need to sort the table data by multiple columns when setting column's sort attribute to be 'custom' (to sort in back-end). Though it's possible by writing code, it seems more elegant if it's supported natively by the library itself.

**Comment by dhthomas76** [comment]
I agree with this feature request. We're porting most of our applications over to Vue.js from AngularJS, and the angular-ui grid (http://ui-grid.info/) we're currently using supports multi-column sorting natively.  Having this feature supported by el-table natively would be a huge help to our users because without it they would lose functionality they currently have today.

**Comment by iamkun** [comment]
duplicated #14398
