### ISSUE TITLE
[Feature Request] DatePicker with "custom label" attribute

### ISSUE THREAD

**Issue by jpenna** [ElemeFE/element#14612]
### Existing Component
Yes

### Component Name
DatePicker

### Description
I want to use the DatePicker for `type=week`, but I don't want to show the week number to the user. 
Instead, I want to show a range of dates (`Mar 05 - Mar 12`) in the input.

I see 2 ways to handle this:

1. Accepting a new property called `label` (following the nomenclature used for `<el-option />` in `<el-select />` components), which receives a string to be presented in the input.
2. Format accept a separator character (`;`, for example), which will be used to format ranges: the first part for `start` and the second for `end`. `type=week` would be one of the use cases, but `datetimerange / daterange/ monthrange` would use it too.

I can do it, but I would like some feedback about the feature and if there is already some workaround for it.

**Comment by wacky6** [comment]
There is plan to support custom format / parsing of input field. In the future, you should be able to write custom parser/formatter:

```
format( internalDate ) => "2019 Mar 05 - 2019 Mar 12"
parse( "2019 Mar 05 - 2019 Mar 12" ) => internalDate
```

To be able to format and parse, the year 2019 can not be omitted.
To be able to display the text, but not accepting user input, the year 2019 can be omitted.

We may also change `type=week`'s bounding value to an array. Current way of using a single date to represent a week is troublesome with `first-day-of-week` prop.

---

You can track future date-picker plan at https://github.com/ElemeFE/element/issues/9878 . Note we currently do not have the resource to implement these changes, expect next major after at least one year.

**Comment by jpenna** [comment]
True, unless we have 2 separate models for the dates (manipulation and display), we need to include the year in the value.

I decided to hide the picker element and show a text which triggers the panels, then I can show any value for date I want.

If you think there could be included a parser for a week range in a minor release, I can work on it. I could request a separator from the user (-, /, <->, ~...) and use it to split the string, the 2 resultant values can be passed to the current format function. What do you think?

**Comment by wacky6** [comment]
I won’t recommend doing so. Current parser/formater is simply a wrap around fecha(a date formatting library). Adding something else can be confusing to users and developers. 

You can see the week format now is already messy. 

This cause edge cases to internal modules, which assumes certain conventions about parsing/formatting code (i.e. return / process Date instance).

In addition, it only use a single date to represent an entire week. As a result, it ignore first-day-of-date.

I won’t be bothered to work around all those problem caused by historical bad designs. It is not cost effective. 

I’d rather fix the design some time later, do it right, then add custom parsing/formatting feature.
