### ISSUE TITLE
[Datepicker] Allow selecting all dates in date-table for date range picker

### ISSUE THREAD

**Issue by abiaskosty** [ElemeFE/element#1506]
### Reproduction Link
http://element.eleme.io/#/en-US/component/date-picker#date-range

### Steps to reproduce
Open date range picker. See two date-table's  are shown: for current and next month. Each table shows its month dates + rest of previous and beginning of next month.

### What is Expected?
When clicking on any date that is shown it should become selected.

### What is actually happening?
It's not possible to select any date for rest of previous month and beginning of next month in each date-table.

In case when date range picker permits only past dates it leads to usability issue. If now is a first date of the month by default user won't be able to select any date except of 'Today' and he almost always has to navigate to previous month to select a range.

**Comment by reverland** [comment]
I don't think its a good idea, however,

It just like bootstrap date range picker does

http://demo.improvely.com/reports/webshop/ads?imt=1&utm_campaign=Date+Range+Picker&utm_source=Site+Ads&utm_medium=Banner&utm_content=Blog+Demo+Image

However, when you click one previous day and click a rest day, things get a little weired.

I think a good UI should always tell user explicitly to do something and get expected behaviour, It may makes a component more complex and buggy than it help user.

By the way, If one really want to skip navigate to previous month, he can choose flatpickr's way. I think its sweet, but I prefer element ui way to hide previous or next days

https://chmln.github.io/flatpickr/

**Comment by abiaskosty** [comment]
I agree, bootstrap date range picker behavior is not the best. It's confusing because, when date is selected from the end of previous month, picker jumps to that month. It would not be so confusing if it just mark that date as selected.

I like the way element ui date picker works but it's strange that range picker doesn't allow to select date from rest of previous month while single date picker does.

**Comment by reverland** [comment]
A little if previous can be marked as select in date range picker, you can't highlight and what you click right may jump to left ...  but it wont make it confusing in date picker

![screenshot from 2016-12-02 00-02-14](https://cloud.githubusercontent.com/assets/1418726/20801081/aeb64132-b822-11e6-84a6-ffc22ee4d4de.png)

however, maybe you can checkout https://ant.design/components/date-picker/, it may handle date range selection in ways of you suggested, and i think it greatly handled it

**Comment by abiaskosty** [comment]
@reverland does Element UI accept the same behavior as ant date picker. I would like to contribute to implement it.

**Comment by reverland** [comment]
@abiaskosty

I don't know, you may @Leopoldthecoder

**Comment by acupt** [comment]
俺也一样！
