### ISSUE TITLE
[Bug Report] "input" event of el-input-number is automatically emitted when first loaded

### ISSUE THREAD

**Issue by 9kg** [ElemeFE/element#15239]
### Element UI version
2.7.2

### OS/Browsers version
Mac OS 10.14/Chrome 73

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mxfc211/9tz62dbw/

### Steps to reproduce
See alert output

### What is Expected?
the same as el-input, Don't automatically emitted when first loaded

### What is actually happening?
diffrent with other form input, "input" event of el-input-number is automatically emitted when first loaded

**Comment by island205** [comment]
Sorry, we have no plan to support this, maybe cause breaking change.

**Comment by hybridwebdev** [comment]
This issue shouldn't be closed, and needs to be looked at/addressed. It indeed is an issue for the  input to emit an event on load for a number of reasons. 

1) it's a performance hit. Say you render a form with 20 number inputs. Well, that's 20 events that fire, potentially causing 20 mutations (see below).

2) It forces the field to assume a number of 0, which, if the field doesn't have an initial value, results in a mutation as the value of the v-model field has changed because of the event firing. This also of course means the value of the input changes, meaning the field re-renders causing yet another event to fire. This means that you've now got an n(1) problem where each number field can potentially fire 2 events just for rendering the field, which itself is an issue, in addition to any other side-effects (eg anywhere else the app uses that value) will now re-render.

Essentially because of these issues, the number field is essentially unusable.
