### ISSUE TITLE
el-select @change event is broken since 1.0.4

### ISSUE THREAD

**Issue by selfcatering** [ElemeFE/element#1632]
### ElementUI version
1.0.4 and 1.0.5

### OS/Browers version
Windows 10/Chrome 54.0.2840.99 m

### Vue version
2.1.4

### Reproduction Link
https://jsfiddle.net/hq4scjto/1/

### Steps to reproduce
Select any of the options within the selectbox. This worked perfectly up until 1.0.3.

### What is Expected?
Change event handler should be invoked

### What is actually happening?
Change event is ignored

**Comment by Leopoldthecoder** [comment]
I think you are using it wrong.
```html
<el-select :value="value" @change="update">
```
To bind a variable to Select, one should use `v-model`, not `:value`. And, inside the `update` method:

```javascript
update: function (selected) {
  value = selected
}
```
I wonder what the purpose of this callback is. Because `selected` is always equal to `value` when the `change` event fires. Besides, to access `value`, one should use `this.value`. A working demo: https://jsfiddle.net/hq4scjto/4/

Also, 1.0.3 doesn't work perfectly in this case: https://jsfiddle.net/hq4scjto/5/ . You can see from the console that `this.value` never changes.

**Comment by selfcatering** [comment]
Sorry but I'm using vuex and` v-model` simply does not work in this scenario. As far as I know v-model is just a syntactic sugar to binding a value along with a change event so I was expecting this to work and it actually did. I was using the `@change` event and it worked perfectly with vuex mutations. Same for `:value` with vuex getters. 1.0.4 broke it for sure. So is it something that you would be willing to take a look at?

**Comment by Leopoldthecoder** [comment]
In this case, try changing `change` to `input`: https://jsfiddle.net/hq4scjto/6/
Select without `v-model` should not fire `change` event (it's actually a bug if version prior to 1.0.3 does). #1508 talks about a similar scenario.

**Comment by selfcatering** [comment]
It makes sense now. Swapping `change` to `input` works like a charm. Thanks for your help.

**Comment by weiwenhao** [comment]
![image](https://user-images.githubusercontent.com/24819514/49218413-53a5ea00-f40b-11e8-80d4-483165d268c2.png)
My input will be triggered,But when the input triggers the update of the data source,Value is not re-rendered
