### ISSUE TITLE
Custom component as el-table-column being displayed at the wrong position

### ISSUE THREAD

**Issue by plrenaudin** [ElemeFE/element#1638]
### ElementUI version
1.0.4 

### OS/Browers version
Linux/Chrome 54

### Vue version
2.0.1

### Reproduction Link
http://jsfiddle.net/tq03bg9x/

### Steps to reproduce
Create a custom component being a el-table-column
Add it to a table after the other columns

### What is Expected?
The custom component column is displayed at the end

### What is actually happening?
Ths custom component column is displayed before the last column

**Comment by Leopoldthecoder** [comment]
I suppose `el-table` can't be nested with any elements other than `el-table-column`.

**Comment by plrenaudin** [comment]
It considers the nested element to be a subColumn of the table because the parent !== owner (https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js#L171) maybe it's a reason for displaying it like this.

Any idea how you could extract a different type of column into a component?

**Comment by QingWei-Li** [comment]
It works with `scoped slots`

**Comment by sobolevn** [comment]
Also struggling to make it work. I have the same issue: ordering is broken.

@QingWei-Li providing some more information about how to make it work with `scoped slots` would be very nice.

**Comment by minikiller** [comment]
I faced same problem, who can help me to solve? thanks!  @sobolevn @plrenaudin   Do you make it work?

**Comment by plrenaudin** [comment]
I couldn't fix it, had to duplicate code instead of using a custom component :-(

**Comment by minikiller** [comment]
please help us to solve this problem. @Leopoldthecoder @QingWei-Li

**Comment by cmrd-senya** [comment]
This can't be cleanly solved using scoped slots, since using scoped slots requires you to define `el-table-column` in each place with the scoped slot, so to embed each column-component you have to write at least 5 LOC instead of 1, not to say that `el-table-column` properties (like `label`) can't be DRY this way - you have to repeat them at each usage occasion.

I used a workaround for that, to create a column of width `1` before the component I insert, so that visually it looks like the component is in the proper place:
```vue    
    ...
    <el-table-column prop="address" label="Address" :formatter="formatter" />
    <el-table-column width="1"/>
    <tag-column></tag-column>
  </el-table>
```

But it is stupid that there is no clean way to make it work as expected. This issue must be reopened.
