### ISSUE TITLE
textarea编辑的时候，无法改变值

### ISSUE THREAD

**Issue by wufei19920201** [ElemeFE/element#16599]
element-ui版本号：2.9.1；
在表单中，input类型为textarea，编辑的时候，数据有回显，但是就是不能操作该输入框

**Comment by southfly** [comment]
I found this problem too , when i change the latest vue.js (, not use vue.min.js) , this warning appeared .

<el-input v-model="item">: You are binding v-model directly to a v-for iteration alias. This will not be able to modify the v-for source array because writing to the alias is like modifying a function local variable. Consider using an array of objects and use v-model on an object property instead.

https://test.hisouth.cn/element/textarea/
