### ISSUE TITLE
[Feature Request] expand tree node by key programmatically

### ISSUE THREAD

**Issue by jhoogeboom** [ElemeFE/element#16977]
### Existing Component
Yes

### Component Name
el-tree

### Description
My use case: I use setCurrentKey to select a tree node based on external input (corresponds to selection in another div) but this can be a nested child that is hidden because it was not expanded before. I would like to expand all parents of that programmatically selected node.

**Comment by haoranyu** [comment]
Similar to `active` state, `current` is just a visual state of a tree node which only affect the CSS class attached on the node. If you use setCurrentKey to pass in a key of a node, the node on the tree will be highlighted.

What you need might be solved by the following steps:

1. Set property `auto-expand-parent` on tree component.
2. Set `default-expanded-keys` with an array containing all [node ids] which correspond to nodes you want them to be expanded. If any node id in the array is not a leaf node, all ancestors will be automatically expanded since you already set `auto-expand-parent` to true in STEP1.

Checkout the demo:
https://codepen.io/haoranyu-the-typescripter/pen/gOYWmba

**Comment by jhoogeboom** [comment]
Thanks for taking the time to think about this and making the demo! I was already using auto-expand-parent, but I really glossed over that default-expanded-keys is also reactive, ea. it's not only on initial load that this default is set.

For now I've ended up forking element and made an expandKey function since I also needed to set multiple keys as current.

**Comment by haoranyu** [comment]
`default-expanded-keys` is truly not a good naming if we could and somewhat should manipulate the value after initial load. 

It might be a good idea if you could contribute to the component and add a method like `setExpandedKeys`.

**Comment by jhoogeboom** [comment]
Yeah the naming threw me off there. Would gladly contribute the changes I made around key expansion. Should anything be done about the name of `default-expanded-keys` as well when we add the more explicit `setExpandedKeys`? Or should the functionality of `default-expanded-keys` be changed to reflect the current naming?

The second feature I've added is having multiple current keys, is this interesting to add as well? probably better in a different feature/pull-request.

**Comment by luckyCao** [comment]
pr welcome

**Comment by chengwb53** [comment]
> `default-expanded-keys` is truly not a good naming if we could and somewhat should manipulate the value after initial load.
> 
> It might be a good idea if you could contribute to the component and add a method like `setExpandedKeys`.

and add method `getExpandedKeys`

**Comment by chengwb53** [comment]
> Yeah the naming threw me off there. Would gladly contribute the changes I made around key expansion. Should anything be done about the name of `default-expanded-keys` as well when we add the more explicit `setExpandedKeys`? Or should the functionality of `default-expanded-keys` be changed to reflect the current naming?
> 
> The second feature I've added is having multiple current keys, is this interesting to add as well? probably better in a different feature/pull-request.

and add method `getExpandedKeys`
