### ISSUE TITLE
[Bug Report] Custom validation rules demo run twice validations for the one which is the last input

### ISSUE THREAD

**Issue by JethroChiang** [ElemeFE/element#17127]
### Element UI version
2.11.1

### OS/Browsers version
chrome 76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jethrochiang/pen/pozNqQM?editors=1111

### Steps to reproduce
1. click the age input
2. click submit

### What is Expected?
console.log print once

### What is actually happening?
console.log print twice

**Comment by a631807682** [comment]
the order event when click button is
1. input blur
2. button click

input blur excute input component validate, and then button click excute full form validate.
i don't think it a bug because the rule is setting by user, and we can't controll what use will do after blur, just like change filed value.

```
...
this.ruleForm.age += 100
this.$refs[formName].validate((valid) => {
...
```

**Comment by JethroChiang** [comment]
thanks
