### ISSUE TITLE
checkbox 组件在路由切换的时候报错

### ISSUE THREAD

**Issue by microacup** [ElemeFE/element#1717]
官网例子Table带checkbox。Chrome下面出现此问题。IE没有。

三个页面，一个页面含有上述组件，另外两个没有，使用了vue-router，在切换的时候出现此问题。

```
	    store: function store() {
	      return this._checkboxGroup.value; // 这里undefined
	    }
```

**Comment by EdenSpark** [comment]
嗯，同样出现了此问题，多个地方使用都是这个情况，但checkbox的值可以获取到

**Comment by QingWei-Li** [comment]
可否给一个 demo？官网的例子没有出现类似问题

**Comment by baiyaaaaa** [comment]
官网例子没有出现问题呀

**Comment by hopkinson** [comment]
我也出现了。就是使用了带有checkbox的table时 切换路由出现了value undefined

**Comment by Leopoldthecoder** [comment]
官网例子就有带有 checkbox 的 Table，但是切换路由时没有报错。所以还是需要各位提供一个 demo。

**Comment by yelingfeng** [comment]
我这也会莫名报个这个错

**Comment by yelingfeng** [comment]
退回1.0.5 不报错了

**Comment by microacup** [comment]
代码改了一堆，demo还没准备好，提供一个绕路思路吧，参考http://microacup.top/2016/12/14/vue-element/ 第一个问题

**Comment by donlzx** [comment]
Had the same issue.

Upgrading vue/vue-template-compiler/vue-loader packages to the latest versions, and then reinstalling element-ui solve it (maybe temporarily).

**Comment by baiyaaaaa** [comment]
@microacup 能提供一个demo么

**Comment by donlzx** [comment]
Had the same issue.  Below are some analysis and a possible fix.

In [get() function](https://github.com/ElemeFE/element/blob/master/packages/checkbox/src/checkbox.vue#L54) of the the "model" computed property in checkbox.vue
```
get() {
  return this.isGroup ? this.store : this.value;
}
```
Because this.isGroup is a computed property and may be cached, while this.isGroup is true,  this._checkboxGroup may already be null (destroyed).

The following fix for the get() function works for me:
```
get() {
  return (this.isGroup && this._checkboxGroup) ? this.store : this.value;
}
```

**Comment by baiyaaaaa** [comment]
@donlzx thanks! seems to be the problem and i will fix it

**Comment by baiyaaaaa** [comment]
@microacup @EdenSpark 可以在1.0.8的版本验证下，今天会发版，谢谢
