### ISSUE TITLE
[Bug Report] Slider visual part not updating when model is updated from another input

### ISSUE THREAD

**Issue by nielslucas** [ElemeFE/element#17558]
### Element UI version
2.12.0

### OS/Browsers version
Mac / Chrome / Version 76.0.3809.132 (Official Build) (64-bit)

### Vue version
2.5.22

### Reproduction Link
https://jsfiddle.net/j6rf5vus/1/

### Steps to reproduce
1: create a data properties as array: sliderValue: [0, 100];

2: create a el-slider with range and attach a v-model=sliderValue

3: create a el-input-number with the same v-model first value v-model=sliderValue[0]
    create a el-input-number with the same v-model second value v-model=sliderValue[1]

4: run app and change de numbers within the el-input-number

### What is Expected?
el-slider using the v-model update to update the visuals

### What is actually happening?
its looks like the v-model values do update but the slider visuals don't.

**Comment by a631807682** [comment]
Seems may need "two-way binding", but two-way binding can create maintenance issues, because child components can mutate the parent without the source of that mutation being obvious in both the parent and the child.

So i suggest to execute `setValues` method by yourself.

https://jsfiddle.net/631807682/80xzgpwj/2/
