### ISSUE TITLE
[Bug Report]  The type definition of `$loading` conflicts with Nuxt.js $loading

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ElemeFE/element#17630]
### Element UI version
2.12.0

### OS/Browsers version
Any

### Vue version
2.6.10

### Reproduction Link
https://github.com/sirixdb/sirix-web-frontend

### Steps to reproduce
1. Clone the repository: `git clone https://github.com/sirixdb/sirix-web-frontend.git`
2. `npm run dev`

### What is Expected?
Start without an exception.

### What is actually happening?
TS2430: Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Property 'open' is missing in type 'NuxtLoading' but required in type '{ open: (params: LoadingConfig) => { close: () => any; }; }'.

**Comment by simhol** [comment]
I second this

**Comment by dmix** [comment]
This is quite a serious issue, you basically can't use Element with Nuxt and Typescript...

**Comment by JohannesLichtenberger** [comment]
Yes, basically as I'm just starting with the front-end I'm thinking about switching to another UI-framework. Don't think this will be fixed somehow in the near future :(

**Comment by Borisstoy** [comment]
Same here! Can't find my way around this!

**Comment by Borisstoy** [comment]
> Yes, basically as I'm just starting with the front-end I'm thinking about switching to another UI-framework. Don't think this will be fixed somehow in the near future :(

Same here, I need to quickly move forward, I switched to Element from Vuetify. Considering switching back!

**Comment by JohannesLichtenberger** [comment]
I also consider to switch / maybe everyone using Nuxt currently in conjunction with Element-UI...

**Comment by Borisstoy** [comment]
Interesting thread @JohannesLichtenberger [here](https://github.com/nuxt/typescript/issues/49).

Nuxt will migrate to `$progress` instead of `$loading` in Nuxt 3.0 (doesn't solve immediate issue).

In the meantime... Sweeping the dust under the rug ([By P-de-jong](https://github.com/nuxt/typescript/issues/49#issuecomment-471277645)).

Change your tsconfig.json:

```
"compilerOptions": {
    "skipLibCheck": true
}
```

**Comment by JohannesLichtenberger** [comment]
Yeah, but that's also only a workaround, but well...

**Comment by menthol** [comment]
Because I needed `skipLibCheck` to false, I used the following :
`tsconfig.json` :
```
"paths": {
      "element-ui": [".sink.d.ts"] // empty file
    }
```

**Comment by georgyfarniev** [comment]
Cast @island205, please reply guys! Please don’t abandon element-ui, people need it.

**Comment by JohannesLichtenberger** [comment]
I have the impression, that it's not really maintained at the moment!? At least also the commits are missing it seems...

**Comment by georgyfarniev** [comment]
@JohannesLichtenberger it’s unclear for me as well. Mostly they ignore issues and PRs and just push commits about once a month. State of framework is unclear. But despite minor bugs, it’s one of best frameworks I ever saw for vue. I think if it will be abandoned, it could be forked and supported by other people.

**Comment by JohannesLichtenberger** [comment]
Oh okay, I'm very new to the frontend world in general, but I've heard, that also Boostrap.js and the other UI-frameworks are used a lot!? That said, yes... I guess as it has over 40000 stars, it's simply going to be forked. At least it seems strange that such a big framework is not really maintained judging the commits and PRs and so on...

**Comment by georgyfarniev** [comment]
@JohannesLichtenberger element is best ui framework imo. Only not well maintained and doesn’t have responsive design. I have thoughts on forking it and fixing some of it bugs, because developers seems to be unavailable even for PRs. The other frameworks such as quasar or vuetify based on material design, which isn’t good for desktop IMO.

**Comment by Borisstoy** [comment]
As matter of fact, I've been using Vuetify for a quite a few projects and was very happy about it. Only thing as mentioned previously, is that look and feel is more suitable for desktop.

You can style override styles easily, it offers awesome responsive, spacing helpers classes, full components library. You can build whatever you want in no time with very decent look and feel.

I chose Element because of its simplicity and nice looking, disappointed by the lack of support tho. I'll switch back to Vuetify.
