### ISSUE TITLE
[Bug Report] popconfirm listener event invalid

### ISSUE THREAD

**Issue by hn4930** [ElemeFE/element#18265]
### Element UI version
2.13.0

### OS/Browsers version
win10  10.0.18362.476 / Chrome/77.0.3865.120

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/edc286sh/

### Steps to reproduce
There is no description of events in the documentation.
In the source code, the use of hump mode to emit events, HTML is case insensitive back to use the "@" mode to listen to events invalid.
=======================================================================================================
首先文档文档中没有关于事件的描述
然后源码中使用了驼峰方式发布事件，html是大小写不敏感回导致使用"@"方式监听事件无效

source code/源码
  methods: {
    confirm() {
      this.visible = false;
      this.$emit('onConfirm');
    },
    cancel() {
      this.visible = false;
      this.$emit('onCancel');
    }
  }

### What is Expected?
使用”@“监听事件
Use "@" to listen for events

### What is actually happening?
不能使用”@“监听事件
You cannot use "@" to listen for events

**Comment by lambal** [comment]
Same problem, case insensitive

**Comment by weimengxi** [comment]
console_runner-35ce412171641ff1bf5aafef664326622ab85fdc72688d6861505d88ff7e036f.js:1 [Vue tip]: Event "onconfirm" is emitted in component <ElPopconfirm> at packages/popconfirm/src/main.vue but the handler is registered for "onConfirm". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "on-confirm" instead of "onConfirm".
