### ISSUE TITLE
[Bug Report] When the Tag of the multiple selector is too long and set collapse-tags, it exceeds the select component

### ISSUE THREAD

**Issue by Undefined100** [ElemeFE/element#21290]
Element UI version
2.15.6

OS/Browsers version
92.0.4515.131

Vue version
2.6.14

Reproduction Link
https://codepen.io/undefined100/pen/PojzQwL

Steps to reproduce
Choose the first option with longer content(长文本长文本长文本长文本长文本长文本长文本长文本长文本长文本长文本长文本)，and choose other option

What is Expected?
I hope it can be constrained inside the select component. 

What is actually happening?
When the value of the option is too long, the width of the tag after the multi-selector is selected will exceed the select component

**Comment by JackDan9** [comment]
`collapse-tags` Whether to support the configuration number. For example, `maxTagsNumber` indicates the number that I need to select to display ?

**Comment by akki-jat-qlik** [comment]
I am facing the same issue.
@iamkun  - I will be working on this issue. Let me know if anyone else is working on the same.

**Comment by akki-jat** [comment]
I am facing the same issue.
@iamkun - I will be working on the same. Let me know if anyone else us working on it/

**Comment by akki-jat** [comment]
> `collapse-tags` Whether to support the configuration number. For example, `maxTagsNumber` indicates the number that I need to select to display ?

@JackDan9 - You should open it as new feature request.

**Comment by JackDan9** [comment]
OK, Thanks!
&nbsp;

JackDan 单军军
Blog 博客
Github 代码仓库
Work In&nbsp;EasyStack
Tel: +86 13027710816
***@***.***
Girlfriend: 王凤凤
Motto: No Pains! No Gains! 一分耕耘一分收获



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Akshay ***@***.***&gt;; 
发送时间: 2021年11月26日(星期五) 凌晨2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ElemeFE/element] [Bug Report] When the Tag of the multiple selector is too long and set collapse-tags, it exceeds the select component (#21290)





  
collapse-tags Whether to support the configuration number. For example, maxTagsNumber indicates the number that I need to select to display ?
  
@JackDan9 - You should open it as new feature request.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
