### ISSUE TITLE
[bug report] fixed columns without data cannot drag the horizontal scroll bar

### ISSUE THREAD

**Issue by PL-FE** [ElemeFE/element#21300]
### Element UI version
2.15.6

### OS/Browsers version
windows10/ Google Chrome-92.0.4515.159

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/samlldevel/pen/WNOGYGo

### Steps to reproduce
1. 无数据/No data
2. 固定列/Fixed column
3. 列名足够长，产生水平滚动条/The column name is long enough to produce a horizontal scroll bar

### What is Expected?
无数据的固定列依然能够正常拖动滚动条/Fixed columns with no data can still drag the scroll bar normally

### What is actually happening?
无数据的固定列下的滚动条无法拖动/The scroll bar under a fixed column with no data cannot be dragged

**Comment by xubiu** [comment]
把fixed去掉就可以了

**Comment by PL-FE** [comment]
我需要fixed😂> 把fixed去掉就可以了

**Comment by xubiu** [comment]
fixed并不影响你前面所处的位置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ElemeFE/element] [bug report] fixed columns without data cannot drag the horizontal scroll bar (#21300)





 
我需要fixed😂&gt; 把fixed去掉就可以了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PL-FE** [comment]
> fixed并不影响你前面所处的位置
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "ElemeFE/element"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2021年9月17日(星期五) 下午4:26
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [ElemeFE/element] [bug report] fixed columns without data cannot drag the horizontal scroll bar (#21300)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 我需要fixed😂&gt; 把fixed去掉就可以了
> 
>  
> 
> —
> 
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Triage notifications on the go with GitHub Mobile for iOS or Android.

好像可以，但是体验有点不一致。我通过重写table计算固定列高度的方法暂时解决了。

**Comment by xubiu** [comment]
可以的 ’






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ElemeFE/element] [bug report] fixed columns without data cannot drag the horizontal scroll bar (#21300)





  
fixed并不影响你前面所处的位置
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "ElemeFE/element"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2021年9月17日(星期五) 下午4:26
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [ElemeFE/element] [bug report] fixed columns without data cannot drag the horizontal scroll bar (#21300)
 
我需要fixed😂&gt; 把fixed去掉就可以了
 
—
 
You are receiving this because you commented.
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
Triage notifications on the go with GitHub Mobile for iOS or Android.
  
好像可以，但是体验有点不一致。我通过重写table计算固定列高度的方法暂时解决了。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
