### ISSUE TITLE
import css bug?

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#2142]
>* Install the template

```shell

vue init ddvs/nuxt testeui&&cd testeui&&npm i

```

>* Enter debug mode

```shell

npm run dev

```

This time we can normally open http://127.0.0.1:3000/admin

Because css is the introduction of such

![image](https://cloud.githubusercontent.com/assets/17898715/21580556/dfb8a646-d03a-11e6-976e-829588d18789.png)

But when I recommend the introduction of being given the wrong way
[element-ui init doc](http://element.eleme.io/#/en-US/component/quickstart)

![image](https://cloud.githubusercontent.com/assets/17898715/21580562/30503c36-d03b-11e6-87e7-f64401be8f7a.png)

This is [a nuxt.js the bugs](https://github.com/nuxt/nuxt.js/issues/97)? Or the distribution of the problem I myself

**Comment by Atinux** [comment]
This is from Nuxt.js because we use `vue-loader` and Vue files, so importing CSS in the `<script>` block does not work.

Maybe it can be nice to explain it that if the user use `vue-loader`, it should not import the CSS in the `script` block? http://element.eleme.io/#/en-US/component/quickstart#import-element

**Comment by lincenying** [comment]
ssr下, 不要在script里import css文件, 可以在style标签里@import

nuxt下, css文件可以在nuxt.config.js里配置

https://github.com/nuxt/nuxt.js/blob/master/examples/global-css/nuxt.config.js

**Comment by yuchonghua** [comment]
@QingWei-Li 这样的话[ElemeFE/mint-ui](https://github.com/ElemeFE/mint-ui/issues/548)也要改掉样式应用了？我该如何修改呢
