### ISSUE TITLE
[Select] with `filter-method` regression

### ISSUE THREAD

**Issue by chanand** [ElemeFE/element#2170]
### ElementUI version
1.1.2

### Steps to reproduce
- Set a select element with `filterable` & `filter-method` .
- Type some text to filter.

### What is Expected?
The filter method should be executed, and the default filtering method should be avoided.

### What is actually happening?
The default filtering is not avoided and the entered text is removed.

(This seems to be a regression from `v1.0.7`, this change might be causing it: https://github.com/ElemeFE/element/commit/0ccd537cc840d76915dba816dabb1bf4806133e4#diff-77681c030d3f0bb43a843a628ce7018cR235)

**Comment by Leopoldthecoder** [comment]
Didn't reproduce this issue: https://jsfiddle.net/gbw1jLd4/4/

Could you provide an online demo?

**Comment by chanand** [comment]
@Leopoldthecoder Have a look at this example:https://jsfiddle.net/arn8uwbp/ 
start typing **b** for **beijing**...

I've only removed the undocumented `:key` prop from your example.

**Comment by Leopoldthecoder** [comment]
Ah yes, I guess in this case `:key` is necessary.

`:key` is an attribute used with `v-for` (detail: https://vuejs.org/v2/guide/list.html#key), so I didn't list it in Element's docs since it comes with Vue itself.

If `:key` is not provided, instead of being removed and recreated, `el-option` gets patched while you type, which triggers some of its internal mechanism to empty your input. Just add `:key` to keep Vue from patching `el-option`.

**Comment by chanand** [comment]
That makes sense, but it did work without `:key` on v1.0.7, and it does work without `:key` when `:filter-method`  is not used, so thanks for the clarification 😄

**Comment by Leopoldthecoder** [comment]
Yes
