### ISSUE TITLE
font files path is referred based on current url , but not to fixed path

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#220]
say if i am on page   ```dashboad.dev/admin``` ,  the font file is requested on  ```maldives.dev/admin/32443004c9c1605802e327d9928f6400.woff ```,  instead of requesting on fixed path , any help please

**Comment by QingWei-Li** [comment]
`publicPath` should be the fixed path in your webpack configuration, like https://github.com/ElementUI/element-starter/blob/master/webpack.config.js#L8

**Comment by chagamkamalakar** [comment]
thank you @QingWei-Li, when i tried to do the same thing , does this font file get generated by build or do I need to copy from any location ? as i don't see any files after running gulp . I'm using it with laravel

**Comment by chagamkamalakar** [comment]
@QingWei-Li  any help please here?

**Comment by QingWei-Li** [comment]
Can you please show your gulp configuration?

**Comment by chagamkamalakar** [comment]
module.exports = {
  output: {
    publicPath: '/fonts/'
  },
  resolve: { 
    alias: { vue: 'vue/dist/vue.js' } 
  }
}

**Comment by QingWei-Li** [comment]
@csvwolf Do u have any ideas?

**Comment by csvwolf** [comment]
@chagamkamalakar You can config the webpack according to [this article](http://codesky.me/archives/try-laravel5-vue2-element-en.wind). Sorry for some mistakes in [element-in-laravel-starter](https://github.com/ElementUI/element-in-laravel-starter), I will update and fix the starter later. ( The file-loader has been loaded in `laravel-elixir-vue-2` while reloading it will create new problems )

Are you problem is: the font can be visited in `/` but can't be visited in `/dashboard`, I test my config and it could run correctly in the following routes:

```php
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard/hello', function () {
    return view('welcome');
});
```

Both `/` and `/dashboard/hello` can load the font correctly.

No more output config should be written since the `laravel-elixir` and `laravel-elixir-vue-2` have done for you.

**Comment by csvwolf** [comment]
Starter has been updated, you can have a try: <https://github.com/ElementUI/element-in-laravel-starter>

**Comment by chagamkamalakar** [comment]
thank you @csvwolf .. it sorted out my problem.
