### ISSUE TITLE
[Feature Request] Datepicker selection order

### ISSUE THREAD

**Issue by Lykegenes** [ElemeFE/element#3631]
In the context of asking a user his date of birth, it would be nice to allow him to select the year first, then the month, and finally the date.

This prevents the task of going back 30 years in the date picker by hand.

**Comment by Leopoldthecoder** [comment]
I think Select is more suitable in this scenario

**Comment by newbie78** [comment]
it seems to me a topic starter offered a useful functional. it would be good, through the attributes, to specify what to show by default - years, months or days.
please reopen

**Comment by tiagofscoelho** [comment]
Yes, I also agree that this is a feature that makes . I was expecting that feature on version 2 of element JS. In terms of User Experience its better to have a date picker to select the birthday instead of 3 different selects for year, month and day and makes totally sense to start the picker on the "Year" view in this context. @Leopoldthecoder, do you still think that Select is the best scenario for that?
