### ISSUE TITLE
[Bug Report] Select component with remote search clears what you typed when the value for each el-option is an object 

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#3728]
### Element UI version
1.2.5

### OS/Browsers version
Chrome 56.0.2924.87

### Vue version
2.2.4

### Reproduction Link
[http://jsfiddle.net/nefnnr18/](http://jsfiddle.net/nefnnr18/)

### Steps to reproduce
1) In the select search box, type "j"
2) Wait for the results to populate
3) Type "o"

### What is Expected?
It should list the results for "jo"

### What is actually happening?
It clears out everything you typed.

NOTE: I believe this has something to do with the value for each el-option being an object. If you set the value to "item.id" instead of "item", it works just fine.
Also, you'll notice there are 2 identical arrays: people1 and people2. This is to spoof different arrays of data coming from a server. If you use one array it works fine, so this might have something to do with it as well.

**Comment by Ralf8686** [comment]
I have a same bug. Because called this watcher. https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L87
I think, need add check for remote select
`if (!this.created && !this.parent.remote)`, because remote can give same response, but, when we use `key`, it will be same instance and `this.created` return true.
