### ISSUE TITLE
[Bug Report] upload在before upload时使用clearFiles方法报错

### ISSUE THREAD

**Issue by uedkx** [ElemeFE/element#3918]
### Element UI version
1.2.7

### OS/Browsers version
57.0.2987.98 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/1qrkq5f1/](http://jsfiddle.net/1qrkq5f1/)

### Steps to reproduce
点击上传图片

### What is Expected?
想实现只能上传一张图片，想法是在上传图片时在before-upload处用clearFiles清空已上传的文件列表	。

### What is actually happening?
此时报错了

**Comment by bishanshan** [comment]
因为在handleProgress里面会获取当前准备上传的file对象并修改file status
```javascript
handleProgress: function handleProgress(ev, rawFile) {
    var file = this.getFile(rawFile);
    this.onProgress(ev, file, this.uploadFiles);
    file.status = 'uploading';
    file.percentage = ev.percent || 0;
}
```
可以在handleSuccess里做clearFiles

**Comment by baiyaaaaa** [comment]
目前的设计不支持在 before-upload 阶段进行clearFiles

**Comment by kartsims** [comment]
Could you please translate this to english, I have the same issue...

**Comment by kartsims** [comment]
Anyone who arrives here, this seems to mean : 

> Using `clearFiles` is not currently supported during `beforeUpload` hook

**Comment by kartsims** [comment]
Maybe this should be stated in the docs though

**Comment by Leopoldthecoder** [comment]
@kartsims Yes. You can `clearFiles` in the `on-change` hook.

**Comment by kartsims** [comment]
Thank you, unfortunately this is not enough for my use case.

I need to have only one file uploaded, and the prop `multiple` set to `false` does not seem to work.

I couldn't find a description of the expected behavior for `multiple` in the docs so I looked up the code, and there doesn't seem to be anything attached to this prop, apart from the declaration itself. Should I open another issue ?

**Comment by kartsims** [comment]
FYI my use case : if the uploaded file is a certain type, I cancel the upload. This works fine but I can't clear the files list in the case where :
- there should be only one file
- the file type is right

**Comment by Leopoldthecoder** [comment]
@kartsims `multiple` is a native HTML attribute: http://devdocs.io/html/attributes#multiple-attribute .

In your case, you can bind a variable to Upload's `file-list`. Since you have access to the newly selected file in `on-change` hook, you can assign the variable to that file (of course wrap it in an array) if the file type is right.

**Comment by kartsims** [comment]
Oh ok that may explain why there is no reference to it in the component's code...  but it just doesn't seem to work. I'll let it go if you don't seem to believe that's an issue.

Thanks a lot for your support ! :100:

**Comment by Leopoldthecoder** [comment]
Don't get me wrong, it's just that `multiple` doesn't get to control if you can **upload** multiple files, it only controls if you can **select** multiple files at a time.

**Comment by kartsims** [comment]
Oooh ok I get it now 👌
