### ISSUE TITLE
[Feature Request] Input: add cursor attribute

### ISSUE THREAD

**Issue by Wizr** [ElemeFE/element#4450]
### Existing Component
Yes

### Component Name
Input

### Description
Add an attribute to set the cursor when mouse hovering over.

Sometimes we need other cursor instead of the default one. For example, when typing (or submitted and disabled the input) we show a `wait` cursor to indicate that something is busy running.

**Comment by scscms** [comment]
Add the style to solve [https://jsfiddle.net/aey3c2y2/](https://jsfiddle.net/aey3c2y2/)

**Comment by Wizr** [comment]
@scscms nice work, but it's non-scoped style.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/aey3c2y2/2/

@Wizr you can add any class you want to make it scoped.

**Comment by Wizr** [comment]
@Leopoldthecoder Sorry, properly I misunderstood. I don't think it's scoped style.

document [here](https://vue-loader.vuejs.org/en/features/scoped-css.html)

**Comment by Leopoldthecoder** [comment]
@Wizr Vue's scoped style does not work well with third party components like Element. See #377 for more information.

**Comment by Wizr** [comment]
@Leopoldthecoder Yes, I know. so I suggest a new attribute to set the cursor.

**Comment by Leopoldthecoder** [comment]
No, we shouldn't add attributes just because scoped style's not working, otherwise it'll become too verbose. You need to customize cursor, while other people may want to customize color, font-size, border-radius, or whatever CSS properties they can customize. Having an attribute for each CSS property just doesn't make much sense.

Overriding the original style in a non-scoped style tag is the best solution. If you worry about polluting other inputs, just add a class to your target input.
