### ISSUE TITLE
[Bug Report] el-table set highlight-current-row style problem

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#4459]
### Element UI version
1.2.8

### OS/Browsers version
win10 / chrome 56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/n3cn6aqL/](https://jsfiddle.net/n3cn6aqL/)

### Steps to reproduce
一个表格设置了highlight-current-row和fixed="right", 一个表格设置highlight-current-row

### What is Expected?
两个表格的最右边border都显示

### What is actually happening?
设置了fixed="right"列的表格的右border消失了

**Comment by syn-zeta** [comment]
Boiled-down reproduction: https://jsfiddle.net/n3cn6aqL/1/ (two tables and `highlight-current-row` were irrelevant)

The right border shows up when moving the `fixed-right` table `1px` to the left:
![image](https://cloud.githubusercontent.com/assets/26761352/25422919/7fb28cb2-2a17-11e7-92b7-f299a0429601.png)

Still, this shouldn't happen since the absolutely positioned child is normally contained inside the relatively positioned parent's padding-box.

**Comment by furybean** [comment]
测试了最新的 2.1.0 ，已经无法重现：https://jsfiddle.net/n3cn6aqL/2/
