### ISSUE TITLE
[Bug Report] color selector when the default value is white or white color value, and then click on the right side of the bar transform color type, no effect

### ISSUE THREAD

**Issue by onionyy** [ElemeFE/element#5080]
### Element UI version
1.3.4

### OS/Browsers version
mac10.11.6    chrome55

### Vue version
2.1.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/246/](https://jsfiddle.net/pj71jkyw/246/)

### Steps to reproduce
打开https://jsfiddle.net/pj71jkyw/246/
点击打开颜色选择器
点击右侧变换颜色分类

### What is Expected?
颜色选择框变换成其他颜色区间

### What is actually happening?
没有变化

**Comment by wacky6** [comment]
Looking into it.
Seems need to distinguish internal states from picker's value.

**Comment by wacky6** [comment]
One quick fix:
watch color's "internal" `_{hue, saturation, value, alpha}` props

As far as current implementation goes, inputs are converted to HSV format, then HSV values are used to draw panels, so I don't think it's necessary to keep these props "internal" (and use one extra layer of getter/setter)

What do you think? @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@wacky6 I'll take a look this weekend😂

**Comment by Leopoldthecoder** [comment]
@wacky6 It seems @Kingwl has helped fix this in #5184.

**Comment by wacky6** [comment]
@Kingwl's fix should be ok.

Though I would still suggest that we improve color-picker afterwards (or as a long-term goal), since:

* calling `update()` twice isn't very elegant, though it won't causes problems due to how Vue works
* `_hue` feels like an internal prop, and should not be used outside of color.js

Maybe we could learn from React's one-way down design, reduce the use of watch/reactivity to produce an elegant (or "pure/functional" by React's ideas) solution?

**Comment by Leopoldthecoder** [comment]
@wacky6 I agree. Maybe some other time when we can have more energy on Element🌚.

Fixed in #5184
