### ISSUE TITLE
[Feature Request] Custom sorting for el-table

### ISSUE THREAD

**Issue by fernandobandeira** [ElemeFE/element#5161]
### Existing Component
Yes

### Component Name
el-table

### Description
I want to customize the way the sorting works, ideally I would be able to pass a custom function to be used as a callback instead of the current hardcoded sort function, with this function I would also be able to return plain false, for example, to disable sorting and keep the data as is.

My current usecase is that my data is sorted throught an API, so I want to keep that order, when clicking on a table header with the name 'Date' for example, I will make a request to an API and specify that i want the data sorted by the 'Date' field, the API returns the data in the correct order, the problem is that element UI resorts it after fetching the data...

**Comment by Leopoldthecoder** [comment]
I don't quite get your proposal, i.e. what your API returns, and what your sorting function looks like. A demo would help a lot

**Comment by fernandobandeira** [comment]
For example, consider the following data:

```json
[
  {
    "name": "aaa"
  },
  {
    "name": "NNN"
  },
  {
    "name": "ooooo"
  },
  {
    "name": "ccccc"
  }
]
```

I currently have an API that will sort that if I pass a parameter on my url, so for example:
```
http://example.app/products?_sort=name
```

This will return my data correctly sorted:
```json
[
  {
    "name": "aaa"
  },
  {
    "name": "ccccc"
  },
  {
    "name": "NNN"
  },
  {
    "name": "ooooo"
  }
]
```

On my front-end I'm using element ui ``` el-table ``` with the ``` sortable ``` property to turn the column sortable, I'm using the ``` sort-change``` event to find the correct column and order that should be used for sorting and I send that directly to my API.

My issue here is that el-table reorder the data after i change it with the new data that i get throught my API, this will turn that into:

```json
[
  {
    "name": "NNN"
  },
  {
    "name": "aaa"
  },
  {
    "name": "ccccc"
  },
  {
    "name": "ooooo"
  }
]
```

My proposal is to provide a way to prevent this sorting, I would like to disable this.

I'm ordering the results throught my API mainly because i have many results I'm also paginating throught it...

**Comment by skrichten** [comment]
I'm running into this same issue.  The problem is that the Table component seems to be geared toward only client side data when it comes to sorting and pagination.  If we want to request separate pages from a server, we have to implement our own sorting, otherwise we only sort the current page of data instead of ALL the data. @fernandobandeira is trying to use the built in sorting to get the column and order and sending that to the server, but then the built in sorting functionality is triggered too, which we wouldn't want.  

I'm trying something similar.  I'm not using the built in sort but instead using the header-click event.  So I have to keep track of the sort order on my own.  I have this working, however now I also need to handle the arrow indicators on my own.  I'm having some trouble with that part.  I'm trying to use the render-header function that the el-table-column component exposes.

Getting paginated and sorted data from a server API is very common use case, so there really should be an easier way to handle this.  Vuetify has this feature, but I'm not a fan of the material design style...
https://vuetifyjs.com/components/data-tables

@fernandobandeira here is my header-click handler if it is helpful

```
onHeaderClick(col, e) {
      if (this.sortSelected !== col.property) {
        this.sortSelected = col.property;
        this.sortDirection = 1;
      } else {
        this.sortDirection *= -1;
      }
      this.fetchPaginatedData();
    }
```

**Comment by skrichten** [comment]
Here is an update on my efforts.... This seems kind of hack-ish, but in the header-click handler I set a CSS class on the header that was clicked.  Now I can use CSS to render the arrows accordingly.  I had to set an initial value in the HTML for `labelClassName` to get this to work.

Also, I'm using render-header function on the column elements to output the arrow icons.  The CSS class is just so I can show/hide them when appropriate.

This assumes ref="cTable" on the el-table

```
onHeaderClick(col, e) {
      if (this.sortSelected !== col.property) {
        this.sortSelected = col.property;
        this.sortDirection = 1;
      } else {
        this.sortDirection *= -1;
      }

      this.$refs.cTable.columns.forEach(function (c) {
        c.labelClassName = ""
      })
      col.labelClassName = this.sortDirection < 0 ? 'desc' : 'asc'

      this.fetchData();
    }
```

render-header function...

```
renderHeader: function (creatElement, { column, $index }) {
        return creatElement('div', 
          [
            column.label,
            creatElement('i', {
              class: 'el-icon-caret-bottom'
            }),
            creatElement('i', {
              class: 'el-icon-caret-top'
            })
          ])
      }
```

**Comment by fernandobandeira** [comment]
This has been solved, you can now use ``` sortable="custom" ```
