### ISSUE TITLE
[Bug, Report], Click, the, custom, menu, button, for, the, first, time, callback, function, tree, store.currentNode, attirbute, is, undefined

### ISSUE THREAD

**Issue by qiutuleng** [ElemeFE/element#5504]
### Element UI version
1.3.6

### OS/Browsers version
Linux / Chrome 59.0.3071.109 (Official Build) (64-bit)

### Vue version
2.3.4

### Steps to reproduce
自定义renderContent，代码如官网所示，点击append的按钮时回调方法append里console.log(store.currentNode)为undefined。但是log(store)，在浏览器展开对象时currentNode为正确的node对象，因此BUG可能是传过来的时候Node对象的currentNode尚未成功赋值，在输出的时候对象被更改了就显示正确了

### What is Expected?
正确输出node对象

### What is actually happening?
对象属性不正确

**Comment by Leopoldthecoder** [comment]
For now it seems there is no good way to get `store.currentNode` in the button's click event listener, because `currentNode` is null until the click event bubbles up to the node itself. Using capture in the event listener might work, but unfortunately it's not supported in render functions. So `setTimeout` to the rescue: https://jsfiddle.net/6dwsn44h/
