### ISSUE TITLE
[Bug Report] The checkbox component generated by the render function cannot be sorted or cannot display animated changes

### ISSUE THREAD

**Issue by mqhe2007** [ElemeFE/element#5513]
### Element UI version
1.3.7

### OS/Browsers version
win10 / chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/mqhe2007/yrz5ozgL/](https://jsfiddle.net/mqhe2007/yrz5ozgL/)

### Steps to reproduce
1. 如果通过“checked”属性设置默认选中，
2. 点击“排序”按钮
3. 通过“value”属性设置默认选中，
4. 点击“排序”按钮，可以排序，但是无法改变选中效果

### What is Expected?
选中的checkbox按新顺序排序

### What is actually happening?
checkbox没有排序

**Comment by Leopoldthecoder** [comment]
First of all, you need to add `key` to disable caching. It doesn't matter if you're using render function or plain template, because plain template without keys also fails in the case: https://jsfiddle.net/9y5cojoj/

So updated demos of `checked` and `value` are: https://jsfiddle.net/yrz5ozgL/1/ , https://jsfiddle.net/yrz5ozgL/2/ . Note that when you're using `value`, you should listen to `input` event instead of `change` event.
