### ISSUE TITLE
[Bug Report] Rate element does't show the text value with disabled option

### ISSUE THREAD

**Issue by Koronos** [ElemeFE/element#5630]
### Element UI version
1.3.7

### OS/Browsers version
Windows 10

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/51zfxdte/](https://jsfiddle.net/51zfxdte/)

### Steps to reproduce
Create a element "rate" add texts, option and disabled option in true.

### What is Expected?
It should show the text "Bueno"

### What is actually happening?
it's showing the rate number

**Comment by Leopoldthecoder** [comment]
Actually this is by design: `show-text` on a disabled Rate only displays score on the right side.

I've given it a second thought and maybe this doesn't feel right. Adding another property `show-score` and leaving it to you to decide what you wish to put on the right seem to be a valid solution. Here's the commit: https://github.com/Leopoldthecoder/element-1/commit/e6ddbcb922f447dba630b04f7e6f9624d107ef03

Considering this update is a break change, we'll release it in the next major version.

**Comment by Leopoldthecoder** [comment]
#6295
