### ISSUE TITLE
select component not reactive for updates for list   whereas native select is getting reactive

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#576]
i have ```locations```  in store , 

in my component the code is as follows

```
<el-select v-model="selectedCountryIndex" filterable placeholder="Select country">
              <el-option
                v-for="(country, countryIndex) in locations"
                v-if="!country.country_id"
                :label="country.name"
                :value="countryIndex">
              </el-option>
 </el-select>
``` 

after updating one element i am replacing that element as 
```
   state.locations.splice(index, 1, newLocaiton)  
```
but this element-ui select component not reactive , i checked the same code with native select , but there is no problem

any help please?

**Comment by Leopoldthecoder** [comment]
`v-for` rendered `el-option`s should be keyed:
```html
<el-option
  :key="countryIndex"
  v-for="(country, countryIndex) in locations"
  v-if="!country.country_id"
  :label="country.name"
  :value="countryIndex">
</el-option>
```

**Comment by chagamkamalakar** [comment]
@Leopoldthecoder  no luck .. it's still not reactive ..

**Comment by Leopoldthecoder** [comment]
Check this out: https://jsfiddle.net/488rwjq2/ . It works when `options` is updated with `splice`, and it won't work without line 34.
See if your case has anything different from this demo.

**Comment by Leopoldthecoder** [comment]
Change `:key="index"` to `:key="item.label"` or `:key="item.value"` does the job.

I should have elaborated more about this mechanism. In fact, your `key` for each `el-option` should be unique. Not only among the current `options`, but also before and after you update them. Vue 2.0 only destroys and recreates `v-for` rendered `el-option` when its `key` is changed.

In your demo, `key` is bound to `index` who stays the same after `removeItem` is executed because the indexes are always `0, 1, 2, 3, 4`. This keeps the second `el-option` from re-rendering. Things are different when you bind `key` to `item.value` because it changes from `2` to `a` when you execute `removeItem`.

Actually I made a mistake in my first response. I didn't notice that `countryIndex` is the index of `locations`. Change `:key="countryIndex"` to `:key="country.name"` will work if `country.name` is unique.

**Comment by chagamkamalakar** [comment]
i understood thank you for clear explanation
