### ISSUE TITLE
[Bug Report] tree component example in ElementUI official website has memory leak issue in IE11

### ISSUE THREAD

**Issue by xingchch** [ElemeFE/element#5800]
### Element UI version
1.3.7

### OS/Browsers version
win7 / IE11

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/xccxccxcc/ska4oboj/20/](https://jsfiddle.net/xccxccxcc/ska4oboj/20/) (this is a fake link)

### Steps to reproduce
refresh tree component example in IE11  several times , check the Memory consumption in devtools

http://element.eleme.io/#/zh-CN/component/tree

### What is Expected?
the Memory consumption should be remain constant 
 

### What is actually happening?
the memory consumption increase gradually.

**Comment by xingchch** [comment]
This issue may cause very serious memory leak in IE11, Is there any methods to circumvent this issue?

**Comment by Leopoldthecoder** [comment]
I'm not sure if Element is to blame on this issue because event without Element (but using Vue), memory consumption increases as you reload.

Here's a screenshot of a demo using Vue alone:
![vue](https://user-images.githubusercontent.com/10095631/28740890-ce0262be-743d-11e7-82f6-c359b21e6c04.jpg)

I kept hitting the `run` button every 3 seconds, and the memory consumption has doubled in one minute. You can try it yourself: https://jsfiddle.net/1b7cspxL/1/ .

As a contrast, reloading a demo without Vue does not increase memory consumption.

**Comment by xingchch** [comment]
Verified the homepage of vuejs wich written in vue, (https://vuejs.org/v2/guide)  did not found this issue. 
hit run cause memory leak maybe another story.

**Comment by xingchch** [comment]
This issue still exist (verified 2.0.2) , In fact , It happend not only on tree component example page, but alse other pages.
