### ISSUE TITLE
[Feature Request] The page component needs a disabled property

### ISSUE THREAD

**Issue by hxlniada** [ElemeFE/element#6219]
### Existing Component
是

### Component Name
pagination

### Description
翻页组件在请求数据的时候，有时候并不想用一个大的遮罩层将所有内容罩住，但是又不想用户持续点击翻页按钮。所以需要一个disabled属性来禁用翻页点击。
默认的翻页组件样式的大小与其他组件并不太合适（比如跟按钮放在一起，翻页组件显得太小了）。希望能添加一个能调整翻页组件大小的功能。
这些内容都是翻页组件该有的基本功能，如果你们没时间添加，我可以抽时间提交pr，希望不要再用“因为会使得组件变臃肿所以不添加”而把issue关了

**Comment by kfeng0806** [comment]
Some update of this issue?
Disabled property is necessary on pagination component because you will not want your user make multiple request before previous request is done. The way you can do is just block the hole page, or just disabled the pagination buttons, i think the last will be the best solution.

**Comment by Hi-Linlin** [comment]
support #10006
