### ISSUE TITLE
[Bug Report] Dialog close event not trigger when bind visible without .sync

### ISSUE THREAD

**Issue by Deguang** [ElemeFE/element#6297]
### Element UI version
1.4.1

### OS/Browsers version
Chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/mrku058q/](https://jsfiddle.net/mrku058q/)

### Steps to reproduce
1. bind `:visible="dialogVisible"` without `.sync`
2. click the close button at the top right-hand corner,  the close event not trigger.

### What is Expected?
Whether or not there is a modifier, the close event must be triggered by close button.

### What is actually happening?
with .sync modifier, the event can be triggered. 
without this modifier, can't be triggered

**Comment by Leopoldthecoder** [comment]
In this case, please use `visible-change`: https://jsfiddle.net/mrku058q/1/ .

This is a down side when we try to be compatible with the original usage `v-model="dialogVisible"`. Hopefully this will be improved in the next major version.

**Comment by Deguang** [comment]
@Leopoldthecoder Thanks for you reply

**Comment by Deguang** [comment]
And .... visible-change, will be triggered by unvisible -> visible and visible -> unvisible, can be equal with @close

**Comment by Leopoldthecoder** [comment]
`visible-change` is a temporary event and will be removed in the next major version.

**Comment by Deguang** [comment]
🙄️。。。

**Comment by haffla** [comment]
Because of this it is actually impossible (or isn't it?) to use the dialog component inside another component (children of the main app). With `visible.sync` it throws

`Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "visible"`

https://jsfiddle.net/6f7jvws0/

With `visible-change` it would work, but if that is going to be deprecated, I'm hesitant to implement it.

**Comment by Leopoldthecoder** [comment]
@haffla We're deprecating `visible-change` only because the `close` event will work in this case.
