### ISSUE TITLE
[Bug Report] Select box not displaying labels properly on pre-selected objects in remote mode

### ISSUE THREAD

**Issue by sruffing** [ElemeFE/element#6427]
### Element UI version
1.4.2

### OS/Browsers version
Windows 10 / Chrome 60.0.3112.90

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ruffing232/0m9ru2h5/](https://jsfiddle.net/ruffing232/0m9ru2h5/)

### Steps to reproduce
See JsFiddle.

1. Setup a select box with a remote method returning objects instead of primitive types
2. In v-model variable, add one of the objects with key/value provided

### What is Expected?
The select box could do a pre-query to get the labels for the selected items and display them properly. If the object is provided as a selected value, then a label key could be provided to show instead of simply displaying an empty string.

The following code is in getOption and seems to be causing the empty label to be displayed on first load.
`const label = !isObject ? value : '';
`

### What is actually happening?
The select box with remote query will show the key instead of using the label for the object if the key is used as the selected value. If the object is used with the full label, then there is a tag shown with no label.

In the JsFiddle example, typing a in the first select box actually causes the values in the second to appear. I haven't tracked this, but creating an initialization method for making a remote request by the ids selected when ONLY the ids are provided could be a solution if the developer does not want to maintain complete objects at all times.

**Comment by Leopoldthecoder** [comment]
- In your demo, `this.options` is empty until user typed something to invoke `remoteMethod`. You need to initialize it to let Select know which items are selected, so that it can take these items' labels and put them in the tags.

- If the value is an object (the second Select), `value-key` is required. See the blue tip above the API table: http://element.eleme.io/#/en-US/component/select

- If the value is a string (the first Select), the `value` property for `el-option` should also be a string.

Working demo: https://jsfiddle.net/0m9ru2h5/1/
