### ISSUE TITLE
[Bug Report] Poppover popper-options causes error

### ISSUE THREAD

**Issue by stablegeniusbestbrain** [ElemeFE/element#6666]
### Element UI version
1.4.2

### OS/Browsers version
OSX Chrome, OSX Safari 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/sammie/ondno3oe/](https://jsfiddle.net/sammie/ondno3oe/)

### Steps to reproduce
Bind an object to popper-options declaring modifiers in the format specified by https://popper.js.org/popper-documentation.html#Popper.Defaults

### What is Expected?
Popover appears with offset specified by popper-options

### What is actually happening?
Popover appears at bottom: 0, left: 0.
[Vue warn]: Error in callback for watcher "showPopper": "TypeError: this._options.modifiers.map is not a function"
Javascript error: TypeError: this._options.modifiers.map is not a function

**Comment by sammieedwards** [comment]
The solution was to refactor popper.js as a package dependency instead of relying on an internal, out-of-date popper.js file in src/utils. Then I had to refactor Vue-popper to reference vm.PopperJS.popper instead of vm.PopperJS._popper. 

This required the popper.js to be imported as an es6 native module instead of a commonjs require() module, so its unclear how this might effect server-side rendering (not a feature I happen to care about).

My solution can be found in a fork here, with an example of popover's popper-options in updated documentation: https://github.com/sammieedwards/element

**Comment by groenroos** [comment]
+1. I have the same issue. Refactoring dependency code isn't really an option for me.

**Comment by CarlosOnline** [comment]
Is there a fix for this issue?

**Comment by luogan210** [comment]
这个问题有没有解决啊

**Comment by pixagraphic** [comment]
Could this please be addressed? I can confirm the bug and the solution by @stablegeniusbestbrain works like a charm and looks clean, but obviously I don't want to edit files in my node_modules folder.

**Comment by lusoftware** [comment]
I have the same issue.How to fix it?
