### ISSUE TITLE
[Bug Report] you can active a tab even if it is disabled

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6793]
### Element UI version
1.4.3

### OS/Browsers version
windows10 Chrome70

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/skt4007y/](https://jsfiddle.net/skt4007y/)

### Steps to reproduce
1. the second tab is disabled
2. but it still can be active by setting data.activeName
3. What is Expected?

### What is Expected?
the next tab or no tab will be active

### What is actually happening?
unwanted tab is active for permission controlling reason,i need to disable it,but it is still here

**Comment by syn-zeta** [comment]
>for permission controlling reason
Maybe the content shouldn't be there in the first place if a user is not supposed to see it? Try wrapping the tab's content in a container with `v-if`, so that it is not added to the DOM. If the data really is sensitive then it may be better to not forward it to the client at all as it will be visible in the dev tools' network/sources panels anyway.

Setting a disabled tab as active can only be done internally by the application itself, and not through a regular user interaction, so why should Element prevent that if the developer is allowing it and may even intend it?

@Leopoldthecoder @QingWei-Li Recommend closing?

**Comment by Leopoldthecoder** [comment]
@syn-zeta I agree.
