### ISSUE TITLE
[Feature Request] Focus trap in el-dialog

### ISSUE THREAD

**Issue by zont** [ElemeFE/element#7123]
### Existing Component
Yes

### Component Name
el-dialog

### Description
Current el-dialog not support focus managment. Please add something like https://github.com/theKashey/vue-focus-lock

**Comment by Leopoldthecoder** [comment]
We're aware of this issue. The Dialog may contain basically anything, and when it's nested with elements that have a dropdown menu, e.g. Select, Dropdown, Cascader, etc., you cannot focus and click the menu items if we lock focus inside the Dialog because these dropdown menus are actually children of the body element. So as a tradeoff, we didn't lock the focus.
