### ISSUE TITLE
[Feature Request] Disable submit button in form till fields are invalid

### ISSUE THREAD

**Issue by AmitGuptaMT** [ElemeFE/element#7298]
### Existing Component
Yes

### Component Name
Form

### Description
I need the submit button of form to be disabled till all the form fields are valid. As soon as all user inputs are valid, it should be enabled.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/c02727gp/

**Comment by clementdubois** [comment]
The underlying issue is that aync-validator (used in element form) is... asynchronous and the need is to have an synchronous validation method that we can easily use to disable/enable the submit button.

Is there a way to make this behaviour without having to rewrite all the validators handled by async validator ?
