### ISSUE TITLE
[Bug Report] Memory leak caused by el-select

### ISSUE THREAD

**Issue by STLighter** [ElemeFE/element#7465]
### Element UI version
1.4.6

### OS/Browsers version
Windows 7 x64/ Chorme v61.0.3163.100 x64

### Vue version
2.5.0 (not only)

### Reproduction Link
Momery leak when using el-select: [https://jsfiddle.net/ST_Lighter/tev5L23h/](https://jsfiddle.net/ST_Lighter/tev5L23h/)
No leak when using el-input: [https://jsfiddle.net/ST_Lighter/19uthaf9/](https://jsfiddle.net/ST_Lighter/19uthaf9/)

### Steps to reproduce
Click run button will start a interval. It will update a counter.
Then check the heap snapshot in develop tools ( click gc button before taking snapshot).
( In the 1st link I use el-select and in the 2nd I use el-input, you will find different result)

### What is Expected?
No memory leak in both link

### What is actually happening?
When the code using el-select ( the 1st link) running, the memory using will increase continuing
![using el-select](https://user-images.githubusercontent.com/10627202/31529541-7a1db670-b00c-11e7-89fe-bfbb4a7bcdaa.png)
It not happend when using el-input.
![using el-input](https://user-images.githubusercontent.com/10627202/31529570-97dde536-b00c-11e7-8321-0c902e97fd53.png)

**Comment by badpunman** [comment]
These mostly seem to be cleared up when the component is destroyed. I'm however concerned over what is left after the component is destroyed. There seems to be something related to el-scrollbar element that is leaving vnodes allocated.
![image](https://user-images.githubusercontent.com/937289/32666707-01b1bf42-c641-11e7-92e2-3ef6da753dc1.png)

There is something suspect with the way mouseUpDocumentHandler has $parent scrollbar/main.vue in its context and all. The way this renders and then shares reference to wrap via computed properties is a pattern i'm not familiar with.

**Comment by badpunman** [comment]
Oops, upon further inspection:

These nodes were only kept alive because scrollbar's mouseUpDocumentHandler had itself as context indeed, but since this is a cyclic reference only, browser was able to release them after instructing it to manually do a garbage collection. It's still a bit bad to have such a reference going on though. Not sure how to fix it however.

**Comment by badpunman** [comment]
However, I think I've identified what does cause some leakage here in your scenario, and I had it fixed in my own code while looking at other possible leaks.
![image](https://user-images.githubusercontent.com/937289/32670837-bca6bda0-c64d-11e7-8d88-e4b01ead3bf5.png)
All thanks to this '@@clickoutsideContext' that is added to elements that use this utility.
It it added to elements when they are binded with the directive, however in unbind, it is not cleared up.
I'll submit a pull request to this soonish.

**Comment by STLighter** [comment]
@badpunman Thanks for your help, but it's not work. And you are right that the leak caused by the cyclic struct `children -> parent -> componentOptions -> children -> parent -> ...` . 
I find it caused by the `<transition>` in `select.vue`.
Before I remove it, js heap look like this:
![1](https://user-images.githubusercontent.com/10627202/32711265-21dc5a72-c879-11e7-98a5-cd74ec3a8366.png)
Then I removed the `<transition>`, js heap look like this:
![2](https://user-images.githubusercontent.com/10627202/32711302-5f2744d2-c879-11e7-85d6-6acb26adb16b.png)
It seems to be a bug of vue, I'm not sure about it yet.

**Comment by STLighter** [comment]
I think I almost fixed it. In the directive `clickoutside`, there is a handler reference the old vnode. I tried to update the reference, and it worked! But I don't understand why it makes `<transition>` constructing a link table structure of vnode(might be related to diff algorithm of vnode ?).
After update reference: 
![1](https://user-images.githubusercontent.com/10627202/32717353-50de93ce-c894-11e7-812d-74c3889ec9a5.png)
![2](https://user-images.githubusercontent.com/10627202/32717356-53ee76ba-c894-11e7-9155-42ad2c51ee77.png)

**Comment by Leopoldthecoder** [comment]
#8225 is merged. Does it fix this issue?

**Comment by STLighter** [comment]
Yes, it's fixed.
