### ISSUE TITLE
[Feature Request] Boolean attributes should always default to false.

### ISSUE THREAD

**Issue by jpickwell** [ElemeFE/element#7691]
### Existing Component
Yes

### Component Name
Alert, Autocomplete, AutocompleteSuggestions, Carousel, Cascader, DatePicker, Dialog, Dropdown, DropdownMenu, Form, FormItem, Input, InputNumber, MessageBox, Popover, Popper, Popup, Progress, SelectDropdown, Slider, Switch, Table, TableColumn, TableFilterPanel, TimePicker, TimeSelect, Tooltip, Tree, Upload

### Description
`Boolean` attributes should always default to `false` to avoid unnecessary constant bindings to turn them off. Example:

```html
<!-- Instead of the following: -->
<el-alert :closable="false"></el-alert>

<!-- do the following: -->
<el-alert not-closable></el-alert>

<!-- or change closable to default to false forcing users to mark alerts as closable -->
```

The absence of a `Boolean` attribute implies a `false` value. The presence of a `Boolean` attribute implies a `true` value.

Components with `Boolean` attributes that default to `true` (name in parenthesis is a suggested rename):
* Alert: closable (static or pinned)
* Autocomplete: trigger-on-focus (dont-trigger-on-focus)
* AutocompleteSuggestions: append-to-body (dont-append-to-body) [mixed-in from Popper]
* Carousel: autoplay (manual-play), indicator (no-indicator)
* Cascader: append-to-body (dont-append-to-body) [mixed-in from Popper], show-all-levels (show-last-level-only)
* DatePicker: append-to-body (dont-append-to-body) [mixed-in from Popper], clearable (not-clearable), editable (read-only)
* Dialog: modal-fade (modal-dont-fade or modal-no-fade or no-modal-fade) [mixed-in from Popup], lock-scroll (unlock-scroll or dont-lock-scroll) [mixed-in from Popup], modal (non-modal), modal-append-to-body (modal-dont-append-to-body), close-on-click-modal (dont-close-on-click), close-on-press-escape (dont-close-on-escape), show-close (hide-close)
* Dropdown: hide-on-click (dont-hide-on-click)
* DropdownMenu: append-to-body (dont-append-to-body) [mixed-in from Popper]
* Form: show-message (hide-message or no-message)
* FormItem: show-message (hide-message or no-message)
* Input: validate-events (no-validate-events)
* InputNumber: controls (hide-controls or no-controls)
* MessageBox: modal-fade (modal-dont-fade or modal-no-fade or no-modal-fade) [mixed-in from Popup], lock-scroll (unlock-scroll or dont-lock-scroll) [mixed-in from Popup], modal (non-modal), show-close (hide-close), close-on-click-modal (dont-close-on-click), close-on-press-escape (dont-close-on-escape)
* Popover: append-to-body (dont-append-to-body) [mixed-in from Popper], visible-arrow (no-arrow)
* Popper: append-to-body (dont-append-to-body)
* Popup: modal-fade (modal-dont-fade or modal-no-fade or no-modal-fade), lock-scroll (unlock-scroll or dont-lock-scroll)
* Progress: show-text (no-text)
* SelectDropdown: append-to-body (dont-append-to-body) [mixed-in from Popper]
* Slider: show-input-controls (hide-input-controls or no-input-controls), show-tooltip (no-tooltip)
* Switch: `on-value` is an exception to this rule because it represents a programmatic value and not a flag.
* Table: fit (auto-size), show-header (no-header)
* TableColumn: resizable (fixed-width), filter-multiple (dont-filter-multiple)
* TableFilterPanel: append-to-body (dont-append-to-body) [mixed-in from Popper]
* TimePicker: append-to-body (dont-append-to-body) [mixed-in from Popper], clearable (not-clearable), editable (read-only)
* TimeSelect: append-to-body (dont-append-to-body) [mixed-in from Popper], clearable (not-clearable), editable (read-only)
* Tooltip: append-to-body (dont-append-to-body) [mixed-in from Popper]
* Tree: expand-on-click-node (dont-expand-on-click), auto-expand-parent (dont-auto-expand-parent)
* Upload: show-file-list (hide-file-list), auto-upload (manual-upload)

**Comment by wacky6** [comment]
@Leopoldthecoder 
Will be great to have this in 2.0

**Comment by syn-zeta** [comment]
While some of these props can be looked into, there are many instances where having a default value of `true` is more appropriate -- requiring a majority of users to mark them otherwise isn't very appealing.

> ```html
> 
> <el-alert :closable="false"></el-alert>
> 
> 
> <el-alert not-closable></el-alert>
> 
> <!-- or change closable to default to false forcing users to mark alerts as closable
> ```

Also, it is easier to reason about positively phrased props (think about using light switches labelled "not on" and "not off").

**Comment by jpickwell** [comment]
@syn-zeta, your light switch example doesn't make sense. Also, I did say that to fix this the listed attributes would be renamed.

**Comment by syn-zeta** [comment]
@jpickwell It's an argument for having a prop named `closable` (positive) instead of `not-closable` (negative).

**Comment by jpickwell** [comment]
I would rather have to put `closable` to make an alert closable, or `not-closable` to make it so. So, either the default has to change to `false` or the prop needs to be renamed.

**Comment by syn-zeta** [comment]
Vue has instances of boolean props that default to true and it makes sense since it is applicable to most use cases. Why have another negatively worded prop to complement an existing one?

![image](https://user-images.githubusercontent.com/26761352/32016391-774dc82a-b9e1-11e7-8572-743219c3240a.png)

In this case, you're suggesting have another prop called `not-css`, or forcing all the users to write `:css="true"`? What if they still choose to write `:css="false"`? Or what if they write `:not-css="false"`? By the way, I'm saying another prop because it is possible that some users may still choose to explicitly set some props to true even though they may default to true, perhaps for readability purposes.

**Comment by jpickwell** [comment]
I feel that Vue components are meant to feel like native HTML elements. As such, the HTML standard is quite clear on boolean attributes (https://www.w3.org/TR/html51/infrastructure.html#sec-boolean-attributes).

I understand what you've said thus far, and I agree that some component options (not props) should default to `true`.

Vue's `transition` component's `css` prop is the only `Boolean` prop that defaults to `true` in the Vue library (according to the docs).

**Comment by Leopoldthecoder** [comment]
@jpickwell Thank you for your suggestion and taking time to list all props that default to true.

Our principle when deciding the default value of boolean props is that if that prop is `true` in most scenario, it should default to `true`. And vice versa. For example, in most cases InputNumber comes with the controls, so `controls` defaults to true. In this way, users don't have to write `controls` in their template unless they don't want them, which doesn't happen quite often.

On the other hand, renaming all these props may not be a  good idea because compared to `hide-on-click` and `autoplay`, `dont-hide-on-click` and `manual-play` don't sound as intuitive. Plus, our users will have to spend some time finding-and-replacing these props if we do rename them.

So, I'm afraid we'll stick to the current names.
