### ISSUE TITLE
Under the [Bug Report] complex input box, press the tab key to select the next input box problem (click two times)

### ISSUE THREAD

**Issue by heimuya** [ElemeFE/element#8041]
### Element UI version
2.0.1

### OS/Browsers version
macOS Sierra 10.12.3／Chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/heimuya/pen/EbygMg](https://codepen.io/heimuya/pen/EbygMg)

### Steps to reproduce
1.选择多个复合型输入框组件（可用prepend slot），构建一个form表单
2.在前一个输入框下按下Tab键

### What is Expected?
下一个复合型输入框组件可以通过按下Tab键获得焦点

### What is actually happening?
按下Tab键后，下一个组件的prepend前置内容获得焦点，但是input输入框需要点击第二下才能获取焦点。查看html代码发现复合型输入框的前置或者后置内容div块添加了“tabindex”属性，可能导致首次tab键操作聚焦在前置或后置内容上。

**Comment by Leopoldthecoder** [comment]
前置和后置内容可能是可交互的，所以加上了 tabindex。

**Comment by agustindidiego** [comment]
@Leopoldthecoder 
I'm experiencing the same issue.
The prepend container element has a hardcoded tabindex="0" which generates the element to gain focus on Tab press, and since it is hardcoded it is not possible to change the value.
If someone is using the prepend slot with static content, like an icon, the icon gains focus on Tab press, which is not a desired behaviour.
