### ISSUE TITLE
[Bug Report] el-selection clearable is used together with @change, and when clear, the change event function receives an empty string '' rather than null

### ISSUE THREAD

**Issue by Fangty1** [ElemeFE/element#8856]
### Element UI version
2.0.8

### OS/Browsers version
win7 64

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/xxqxe7Lt/1](https://jsfiddle.net/xxqxe7Lt/1)

### Steps to reproduce
https://jsfiddle.net/xxqxe7Lt/

事件函数：
    	selectionChange: function (value) {
      	console.info(typeof value)
        console.info(value)
        }
清空选项时，期待value 是 null， 而不是 ''

### What is Expected?
https://jsfiddle.net/xxqxe7Lt/

### What is actually happening?
https://jsfiddle.net/xxqxe7Lt/

**Comment by stephsavoie** [comment]
I don't see why it would receive a "null" instead of an empty string here.

The default behaviour is simple but understandable:  Under the hood, clearing an option from the list reset the property value to an empty string then triggers a "change" event (much like a user would select another option).  Finally, "clear" event is triggered.  Since "change" event send the new value as function parameter, it makes sense that you receive an empty string.

But as an future enhancement directly related to your bug report, it would make sense that the "clear" event function receive the selected value before it gets reset, in case the developer would like to handle that value.  Right now, no parameter is defined for "clear" event (at least, from what I've read in the documentation for Element 2.4.1) and you have to keep track of the current value in a separate property as a workaround.

**Comment by binlaniua** [comment]
example:

is java a field is enum

```
enum Status {
   A,
   B
}

class SomethingRequest {
   Status status; 
}
```

is js if is "", it's a error, not mapping any "Status" enum, when post request 
```
{
  status: "" // is error
}
{
  status: null //is success
}
```
