### ISSUE TITLE
[Bug Report]useless attributes are added to datepicker

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#8907]
### Element UI version
2.0.8

### OS/Browsers version
all

### Vue version
2.5.3

### Reproduction Link
https://jsfiddle.net/a2cdp0nL/

### Steps to reproduce
![image](https://user-images.githubusercontent.com/1060733/34187189-1b6e9416-e56b-11e7-94e0-7c534ff72023.png)

![image](https://user-images.githubusercontent.com/1060733/34187206-2b8c0b6c-e56b-11e7-931e-345c6de07224.png)

![image](https://user-images.githubusercontent.com/1060733/34187216-38c7195c-e56b-11e7-8a32-7876e8f544c8.png)

**Comment by Leopoldthecoder** [comment]
`id` and `name` are not useless, you can assign them to a DatePicker so the inner input(s) can have an id or name. The problem is that if you don't assign them, Vue still writes these attributes to the DOM element, and Chrome 63 now warns against duplicate ids when your page has `<input type="password">` on it(https://stackoverflow.com/questions/47863290/error-found-3-elements-with-non-unique-id-input). Honestly there's not much we can do, plus this warning doesn't break anything, so just ignore it.
