### ISSUE TITLE
[Feature Request] el-form-item label click can focus the cursor of the input box

### ISSUE THREAD

**Issue by yoyo837** [ElemeFE/element#8937]
### Existing Component
Yes

### Component Name
el-form-item

### Description
Hope to provide optional configuration，el-form-item label click can activate the input box.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can implement this feature yourself: https://jsfiddle.net/84h6tLu7/

**Comment by raphaelsaunier** [comment]
@yoyo837 You can use a combination of the `for` and `id` properties to achieve that behaviour:

```
<el-form-item label="Label" for="field_id">
  <el-input id="field_id" />
</el-form-item>
```

It's not documented yet, but the `for` prop on `<el-form-item>` is actually passed to the rendered `<label>`. Binding a click listener and using a ref works too, but it seems like the wrong way to go.

This is a clear accessibility/usability issue and it would be nice if Element UI did this automatically for us. However, since `<el-form-item>` can contain multiple input elements, it might be harder to generalise it.

@Leopoldthecoder I'm happy to submit a PR if you reconsider this in the future.

---

Related: https://github.com/ElemeFE/element/issues/1518

**Comment by wacky6** [comment]
My thought is that we stick with for / id, which is how native html works.

**Comment by raphaelsaunier** [comment]
Just for the record, the native `<label>` also works without those properties. See:

> When a <label> is clicked or tapped, and it is associated with a form control, the resulting click event is also raised for the associated control.  
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by yoyo837** [comment]
@raphaelsaunier Well, You are right, but this seems to be a biiiiiiiiiiiiiiiiiig change for `element-ui`.  😄
