### ISSUE TITLE
[Bug Report] How to disable the “status-icon” with “Select” in “Mixed input”？

### ISSUE THREAD

**Issue by skaiy** [ElemeFE/element#9107]
#

### Element UI version
2.0.10

### OS/Browsers version
windows,sogou

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/g8ayby37/2/](https://jsfiddle.net/g8ayby37/2/)

### Steps to reproduce
1. “Select” in “Mixed input”
2. “Select” has default value or disabled state 
3. Form validation has “status-icon”

### What is Expected?
no “status-icon” at “Select”，when has default value or disabled state in “Mixed input”

### What is actually happening?
has “status-icon” at “Select” (when has default value or disabled state)

![20180103105901](https://user-images.githubusercontent.com/2673613/34508578-13d468c2-f07c-11e7-9e65-162d20a94cdb.png)

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/g8ayby37/3/
This bug is not easy to fix.
Form components may only contain one input component in the original design. If we include more than two inputs, it is impossible to know the input that need to be verified. Each input gets [the FormItem from the *inject* option](https://github.com/ElemeFE/element/blob/63fed345e578189d8a1c84ba284368cf843d2389/packages/input/src/input.vue#L102-L109).

But I have a workaround. We can register a component to override the parent component *provide* option

```js
Vue.component('breakForm', {
  provide: {
    elForm: '',
    elFormItem: ''
  },

  render() {
    return this.$slots.default[0]
  }
})
```

[online demo](https://jsfiddle.net/g8ayby37/4/)
