### ISSUE TITLE
[Feature Request] Datepicker userInput validation

### ISSUE THREAD

**Issue by badpunman** [ElemeFE/element#9146]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Current datepicker component is very inadequate when it comes to users writing the dates themselves.
The component only updates the bound value when the user's written value happens to be valid. It does not output any validation error messages. User is allowed to write invalid date without any warning, with previous allowed value being the real bound value. 

There really has to be some kind of pattern developed here that allows for invalid values to be written, form validator to trigger on it, and user experience to be intuitive in regards to this.

If we are using the 'value-format' feature, the user-written value could be maybe bound even when it is invalid. This would allow for validators to check against it directly. This wouldn't really work for the default Date-object bound values however, and could also be unexpected for users who don't use validators and expect the control's outbound values to always be of the valid format.

**Comment by wacky6** [comment]
What's your expected behavior? Clear bound value to null whenever user input is invalid?

**Comment by badpunman** [comment]
Well, that is one of the issues. Setting it to null doesn't really help us indicate to user that his text is not of valid format. At best it would just make it so that the form with optional dates (with invalid text written) pass validation with optional null values. User would just presume his date is of correct format since the form passed.

Maybe it would be necessary to declare a secondary prop to bind the plain userInput that developers can use for their validation rules.

**Comment by wacky6** [comment]
That's a tough question.

I don't think exposing user input to outside world is a good idea because it should be controlled by the component. Besides, Vue does not offer an optional 'v-model' feature, so it's either a event or a `prop.sync`.

* In the case of event, developers need to do all the dirty work validating the value, in someway that may be different from element's logic, so the result may not be accepted by the component.
* In the case of `prop.sync`, it will break all existing code.

One idea could be: when input lose focus, clear invalid user input if it can not be parsed (invalid format, does not match disabledDate constraint, etc). (Similar to input-number)

---

A easier solution might be checking component's `userInput` property, which should be empty if the user input is valid and accepted by the component. (If I recalled the implementation detail correctly)

I suggest you have a look at date-picker's internal states using Vue dev-tools

**Comment by badpunman** [comment]
Well, just clearing it is not user friendly though. It provides no feedback to user how to correct his date-entry, and he loses progress when he has to start typing again.

I didn't really even consider the disabled dates and such.

Exposing some error-state from the component itself would be necessary to keep it simpler then..

**Comment by wacky6** [comment]
The I guess for now you should check the internal states (userInput / displayValue / etc.)

You may also consider using placeholder to indicate the acceptable format: https://jsfiddle.net/scc23ert/

**Comment by AdamSGit** [comment]
Putting it in placeholder, or in a small help text under seems good to me. Also please note that validation shouldn't be part of element.io concern, since the datepicker component work well with vee-validatate, which could be the best option for that.

**Comment by aadjemonkeyrock** [comment]
When manually entering a date you can type any character. it would be good to limit this to digits and separator characters. This way there is less chance you end up with a date that can't be parsed (and is easier for the user)
