### ISSUE TITLE
[Bug Report] No blur event listener in directives

### ISSUE THREAD

**Issue by aaronfulkerson** [ElemeFE/element#9259]
### Element UI version
2.0.11

### OS/Browsers version
Windows 10/Chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://gist.github.com/aaronfulkerson/294d5604a7c989ecdfa965a0aa25affd](https://gist.github.com/aaronfulkerson/294d5604a7c989ecdfa965a0aa25affd)

### Steps to reproduce
1) focus element with directive
2) blur element with directive

### What is Expected?
Expect blur event listener to fire

### What is actually happening?
Blur event listener not firing

**Comment by aaronfulkerson** [comment]
Changing event listener type to 'input' is working.

**Comment by aaronfulkerson** [comment]
My workaround is to attach the event listener to the child input element: el.getELementsByTagName('input')[0]

**Comment by Leopoldthecoder** [comment]
Yes, the outmost element of `<el-input>` is not a `<input>` but a `<div>` wrapper, so you'll have to add the event listener to the inner `<input>` because `<div>`s doesn't have blur events.

This is not a bug. I'm not sure what this directive does, but if you're just trying to listen to `<el-input>`'s blur event, you can simply https://jsfiddle.net/ywg1214q/1/
