### ISSUE TITLE
[Bug Report] Checking tree nodes

### ISSUE THREAD

**Issue by ippei0605** [ElemeFE/element#9350]
### Element UI version
2.0.11

### OS/Browsers version
macOS High Sierra 10.13.2

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/team/jiec_rd/pen/604428fed1d80a4c81d209189ce50902](https://codepen.io/team/jiec_rd/pen/604428fed1d80a4c81d209189ce50902)

### Steps to reproduce
When Level tow 1-1 is checked, Level one 1 is automatically checked.
I do not want Level one 1 to be checked.

Same here.
http://element.eleme.io/#/en-US/component/tree
Checking tree nodes

### What is Expected?
I do not want Level one 1 to be checked.

### What is actually happening?
When Level tow 1-1 is checked, Level one 1 is automatically checked.

**Comment by ngopal1995** [comment]
Hi @ippei0605 .... This may not be an issue since, if root nodes have selection, then parent should also have selection, as per norm. But in your case, the other child are not selected. Instead of tick mark, it could be an indeterminate selection like below.

![issue2](https://user-images.githubusercontent.com/15034669/35109446-6ba9f8c4-fc9c-11e7-81e5-50e47c20a03a.PNG)


(PS: Newbie here. Correct me if i am wrong)
![issue1](https://user-images.githubusercontent.com/15034669/35109339-1709d0dc-fc9c-11e7-9b44-fc22f55ec258.PNG)

**Comment by ippei0605** [comment]
I misunderstood that it was possible to select a sub-node alone. Please close it. Thank you very much.

Best regards,
Ippei

2018/01/19 1:41、ngopal1995 <notifications@github.com>のメール:
