### ISSUE TITLE
[Bug Report] el-select, multiple collapse-tags filterable, longer text is push out select element and input but is push down 

### ISSUE THREAD

**Issue by shridhar18** [ElemeFE/element#9352]
### Element UI version
2.0.8

### OS/Browsers version
All

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/tpttmjuq/8/](https://jsfiddle.net/tpttmjuq/8/)

### Steps to reproduce
1. Select long text first from the option list
2. Enter by typing any other text option available from the option list

### What is Expected?
1. Longer text should not be pushed out of select element
2. Input box for entering text should stay in the same row.
3. Height of select element should not be changed otherwise when select element is used in the grid view it will increase row height   

### What is actually happening?
1. Longer text is pushed out of select element
2. Input box for entering text pushed down if Longer text is selected fist. 
3. Height of select element is changed and when select element is used in the grid view it increases row height

**Comment by Leopoldthecoder** [comment]
You can add the ellipsis if you prefer: https://jsfiddle.net/tpttmjuq/9/ , but widening the component seems to be a better idea: https://jsfiddle.net/tpttmjuq/10/ .

**Comment by vincebanzon** [comment]
Sorry to butt in to a closed issue. But somewhat, this is how I did it.
Max-width should be the widest of the screen (viewport)
but it still isn't enough so I made it scrollable left-right.

.el-select-dropdown__item {
  max-width: 100vw;
  overflow-x: scroll;
  overflow-y: hidden;
}

**Comment by luanki** [comment]
不知道这个能不能解决你们的问题：设置 `.el-select-dropdown` 的 `max-width` 属性为一个较小的值，因为组件会自动设置 `min-width` ;由于我们设置的`max-length`比较小，当 `max-width` 小于 `min-width` 时奇妙的现象就出现了https://jsfiddle.net/4u6b9tye/13/

**Comment by Fadeoc** [comment]
It is really a long time, I am not sure anyone is looking for a solution. 

The fact is, it is not about el-dropdown, but the el-button inside the el-dropdown, so I went looking something can be tuned in el-button.

I tried use _el-button span_ in css, but no luck, seems that css won't apply on the span inside there, maybe I saw once it was applied, but no luck anymore.

I was considering create an clone of the el-button and modify the prop of it, so I can send a style to the span, after a bit thinking the principle of component designing, I am not sure it would be a good idea, because that is a slot in the span.

So as you see, After two hours, suddenly an idea come to me, I could **pass a block element instead of pure text into the slot.**

That is it. 

 ```
   <el-button size="mini" class="el-dropdown-text-con" type="primary">
      <div class="el-dropdown-text">{{selectedText}}</div><i class="el-icon-arrow-down el-icon--right"></i>
    </el-button>
```

Then I can tune as any css as I want to the div in the slot, give it _max-width_ or _overflow:hidden_, or calc or use vue states in the style thus could be dynamic.

**Comment by Lynnze-24** [comment]
This will fix everything for you. Copy and paste these styles in your css file. Cheers!

.el-select > .el-input {
border: 0.1px solid #bfbfbf;
border-radius: 3px;
overflow: hidden;
}
.el-select > .el-input:hover {
border-color: #595959;
}

.el-select > .el-input:active,
.el-select > .el-input:focus-within {
border-color: #409eff;
}

.el-input__suffix {
background-color: white;
width: 40px;
right: 0;
}
.el-input--medium .el-input__inner {
width: 600px; //should be bigger than your text
border: none !important;
}
