### ISSUE TITLE
[Bug Report] Element UI form validation triggers every time when translated validation message changed

### ISSUE THREAD

**Issue by lkmadushan** [ElemeFE/element#9375]
### Element UI version
2.0.11

### OS/Browsers version
Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/rtb0h7z0/13/](https://jsfiddle.net/rtb0h7z0/13/)

### Steps to reproduce
Every time you clicked "change message" validation triggers

### What is Expected?
It shouldn't validate input field when the message changed

### What is actually happening?
It validates input field every time when the message changed

**Comment by Leopoldthecoder** [comment]
This is not a bug.

The change of `this.translate` updates `this.message` because `this.translate` is a dependency of `this.message`. Similarly, the change of `this.message` updates `this.rules`. When `this.rules` is changed, `<el-form>` will validate itself using the new rules.

**Comment by lkmadushan** [comment]
I understood. But let’s say we want to change the validation messages based on the language, in that case every time we changed the language validation triggers. 

Is there any workaround for this?

**Comment by wacky6** [comment]
Right now, no workaround.

Maybe add an option to configure validation on rule change behavior?

**Comment by lkmadushan** [comment]
@wacky6 Can you explain your solution bit further?

Is there any way to translate validation messages in ElementUI?

**Comment by wacky6** [comment]
I just checked the source code, there is a work around in fact. (Added three months ago)

Try `clearValidate` method on form or form-item. **But** it's not perfect: you can clear the validation message after changing the rule, but the validation will still be carried out.

I've added a custom validator to phone. Open the console, you can see the validator being called.
https://jsfiddle.net/b5g0t18r/

---

The problem comes from form's code:

```
watch: {
  rules() {
    this.validate();
  }
},
```

The problem is pretty obvious. When `rules` changes, the form will validate itself.

**Comment by lkmadushan** [comment]
@wacky6 Thank you very much man. You saved my life :) Used clearValidate method for now.

**Comment by Leopoldthecoder** [comment]
We already have a PR for that. Chances are it'll be shipped with the next release.

**Comment by Vekku** [comment]
Whats the status on this. Is this shipped already?

**Comment by bpsilver** [comment]
Didn't see this in the docs, but it is in the code. You can set the `validateOnRuleChange` property of the form to false and it will not fire validation when the rules change.
