### ISSUE TITLE
[Feature Request] Scroll event for table for infinite scolling

### ISSUE THREAD

**Issue by AshwinTayson** [ElemeFE/element#9410]
### Existing Component
Yes

### Component Name
<el-table>

### Description
Is there a possibility to add scroll event to table so that we can detect if scroller has reached end of table. This will be very usable for lazy loading data and appending to the table.

`@header-dragend` (triggers when finish dragging header) doesn't work. I'm not sure if this is used for the same functionality. Docs are not very clear.

**Comment by Leopoldthecoder** [comment]
A demo on lazy loading: https://jsfiddle.net/leopoldthecuber/4ez4j2j4/10/

`header-dragend` triggers when the end user changes a column's width by dragging the column header's border. I'll update the docs to make it clear.

**Comment by syn-zeta** [comment]
@Leopoldthecoder The `append` slot hasn't worked for infinite scroll components for a while now. The plugins expect to be injected as a descendent of the scrolling element, but the `append` slot is outside the scrolling element for Table component.

This is a capture of the fiddle that you posted (notice that the load gets triggered automatically):

![infi](https://user-images.githubusercontent.com/26761352/36703143-1e520b48-1b0f-11e8-8d5e-bf4c12a2e9ca.gif)

**Comment by Leopoldthecoder** [comment]
@syn-zeta The `append` slot works when I posted this fiddle (version 2.0.9): https://jsfiddle.net/4ez4j2j4/32/ , but https://github.com/ElemeFE/element/commit/9b9384214b0f5e718f4e7c67f4483c58743ae6e1 breaks it.

**Comment by syn-zeta** [comment]
Right, because that commit updated the default `overflow` of `el-table__body-wrapper` from `auto` to `hidden` (with `scrollable-y` class added later), so when the infinite plugin is initialized, it is unable to determine the body as the scrolling ancestor.

The plugin provides a way to force-select the scrolling element by adding an attribute, but since `body-wrapper` is inside the Table component, there's no clean way to do that.

![untitled](https://user-images.githubusercontent.com/26761352/36764872-8bc3561c-1be3-11e8-9b7a-8350c6d74b36.png)
