### ISSUE TITLE
[Bug Report] El-select placeholder text is not reactive, doesn't re-translate

### ISSUE THREAD

**Issue by badpunman** [ElemeFE/element#9854]
### Element UI version
2.2.0

### OS/Browsers version
all

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/317/](https://jsfiddle.net/mmx38qxw/317/)

### Steps to reproduce
using vue-i18n@5.x

create el-select element with no explicit placeholder-prop.

change language.

### What is Expected?
placeholder text should change accordingly.

### What is actually happening?
it's always chinese.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by badpunman** [comment]
@Leopoldthecoder 

http://element.eleme.io/#/es/component/select

here's the reproduction link.

**Comment by kevrousso** [comment]
I'm having the same issue, here's the repro link:
https://codepen.io/kevrousso/pen/oEarxM

My app (setup with latest vue-i18n and vuex to manage language) is a bit different than what's on the repro link but it shows the issue clearly I think.

When the app boot up, the locale is set, but whenever you change it dynamically the placeholder for the Select doesn't reflect the correct locale.

However, the DatePicker is picking it up but I assume it's because it's being refreshed on click.
