### ISSUE TITLE
[Bug Report] Select do not update label when multiple options have the same value

### ISSUE THREAD

**Issue by arashm** [ElemeFE/element#9868]
### Element UI version
2.2.0

### OS/Browsers version
ArchLinux / Firefox 60.0a1 (Nightly)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/326/](https://jsfiddle.net/mmx38qxw/326/)

### Steps to reproduce
- Make a select element with options having same value but different labels (Like country codes provided in the jsfiddle).
- Selecting any of the options with same values, won't update the label (many countries have similar country code, e.g. U.S. has country code of  1 but also Virgin Islands, Trinidad and Tobago, Turks and Caicos Islands and they are considered different countries with different iso codes)

### What is Expected?
Even when the values are the same, the select element should update label to the chosen one.

### What is actually happening?
The label is fixed, and won't get updated upon users select.

**Comment by wacky6** [comment]
Sorry, value must be unique. Select's result will only be controlled by `value`.

Otherwise the component's perceived state is not controlled solely by data, but also requires previous state (user input). This is against the principles of Vue / React / MVVM frameworks.

For example, if you set `countryCode` to `1` programmatically,  which one should the component highlight if there are multiple options with value `1`.

**Comment by Leopoldthecoder** [comment]
@wacky6 is right.

@arashm A possible solution for you is https://jsfiddle.net/mmx38qxw/333/ , where `value` can be an object.
