### ISSUE TITLE
[Bug Report] HSV color picker can not input string directly. i can only to pick colors

### ISSUE THREAD

**Issue by yihchu** [ElemeFE/element#9972]
### Element UI version
2.2.0

### OS/Browsers version
mac os 10.13.2/chrome 64.0.3282.186

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1. set color-format = hsv
2. pick a color 
3. modify the string of color, and input 'enter' 
4. the string of color i set disappeared

what i want is to set hsv color by hand

### What is Expected?
the hsv color picker support both picking color and inputing color string

### What is actually happening?
the hsv color picker  only support picking color

**Comment by Leopoldthecoder** [comment]
Now ColorPicker only supports rgb(a) format for manual input. We'll see if we can support more formats.

**Comment by wacky6** [comment]
Interesting feature, how about parsing in a similar way to CSS's color / mimic Chrome behavior?

Is is possible to hack it with a hidden element + getComputedStyle?

```
#rrggbb
rgb(rr, gg, bb)
hsl(hh, ss, ll)
... + alpha channel
```

**Comment by Leopoldthecoder** [comment]
@wacky6  I'm not sure what you meant by "parsing in a similar way to CSS's color", but hacking with a hidden element and `getComputedStyle` cannot work for hsv model since no browser supports such color model. Works for other models, though.

I'm thinking maybe some RegExp testing if the user input is valid in its model can do the job. Internally ColorPicker can convert the value to whatever model it needs.
